/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "⚔️Combat": "⚔️战斗",
    "⏰Seconds": "⏰秒",
    "🧠Study": "🧠学习",
    "🔎Search": "🔎搜索",
    "🔋Energy": "🔋能量",
    "📈Stats": "📈统计",
    "💪Power": "💪力量",
    "Load": "加载",
    "Learn How to Read": "学习如何阅读",
    "Items": "物品",
    "Normal Task": "普通任务",
    "Perks": "特权",
    "Repeat Tasks": "重复任务",
    "Rewards": "奖励",
    "Skill Gains": "技能增益",
    "🎭Charisma": "🎭魅力",
    "Undo": "撤销",
    "Train with Weapons": "武器训练",
    "Controls": "控制",
    "Do Energy Reset": "进行能量重置",
    "End of Content": "内容终点",
    "🌀Attunement": "🌀点化",
    "🗡️Subterfuge": "🗡️诡计",
    "📖Mystery Perk": "📖神秘特权",
    "✨Divine Spark": "✨神圣之火",
    "Artifacts": "神器",
    "Beg for Food": "乞讨食物",
    "Completions": "完成",
    "🔎Search, 🗡️Subterfuge": "🔎搜索, 🗡️诡计",
    "Bonuses not from levels (E.G., from Items and Perks) are not scaled down this way": "不是来自等级的奖励（例如，来自道具和特权）不会按比例减少",
    "Congrats on winning the game. Fow now.": "祝贺你赢得比赛。现在出发。",
    "Cost Estimate": "成本估算",
    "Hide and Seek": "捉迷藏",
    "Join the Watch": "加入守卫",
    "Lorem Ipsum": "Lorem Ipsum",
    "Mandatory Task": "必做任务",
    "Observe Surroundings": "观察周围环境",
    "Read Noticeboard": "阅读布告栏",
    "Skill speed increases 1% per level, while ♟️XP needed to level up increases 2%": "技能速度每升一级增加1%，而♟️升级所需经验增加2%",
    "The speed of Tasks with multiple skills scale by the square or cube root of the skill level bonuses": "多个技能的任务速度由技能等级奖励的平方根或立方根决定",
    "You've reached the end of all content that exists!": "你已经到达了所有存在的内容的尽头！",
    "Zone 1 - The Village": "区域1 -村庄",
    "🍲Food Items": "🍲食物物品",
    "🗺️Move to Zone": "🗺️移动到区域",
    "Bonus": "加成",
    "Item(s)": "物品",
    "No Item to undo": "无物品可撤销",
    "Skill": "技能",
    "Stats": "统计",
    "tasks": "任务",
    "Travel Task": "旅行任务",
    "Undo Last Item Use": "撤销最近使用的物品",
    "🔋Energy goes down over time while you have a Task active": "🔋当你有一个任务处于激活状态时，能量会随着时间的推移而下降",
    "Bonuses to different Task types stack multiplicatively with one another": "不同任务类型的奖励会互相叠加",
    "Current Skill bonuses:": "当前技能奖励：",
    "Disabled until you complete the": "禁用，直到您完成",
    "Disabled until you do your first Energy Reset": "在你进行第一次能量重置之前是不可用的",
    "Item undo is available until you start your next Task": "在开始下一个任务之前，项目撤销是可用的",
    "Items can be used to get bonuses that last until the next Energy Reset": "物品可以用来获得持续到下一次能量重置的奖励",
    "Lets you reopen the last Energy Reset Summary": "让您重新打开上次的能量重置摘要",
    "Lets you Save and Load from disk": "允许您从磁盘保存和加载",
    "Mandatory": "必选",
    "Open Settings Menu": "打开设置菜单",
    "Perks are permanent bonuses with a variety of effects": "津贴是具有多种效果的永久性奖励",
    "Right-click to use all rather than just one": "右键单击可以使用全部而不是一个",
    "The bonuses stack additively; 2 +100% results in 3x speed, not 4x": "加成叠加；2 +100%的速度是3倍，而不是4倍",
    "The bonuses stack multiplicatively; 2 +100% results in 4x speed, not 3x": "奖励以乘法方式堆叠；2 +100%的速度是4倍，而不是3倍",
    "Toggle between repeating Tasks if they have multiple reps, or only doing a single rep": "在重复任务之间切换，如果他们有多个代表，或只做一个代表",
    "Using an Item while already having a Task active will prevent undoing": "在已激活任务的情况下使用项目将阻止撤消",
    "View Last Energy Reset Summary": "查看上次能量重置摘要",
    "When repeating, the Task tooltip will show the numbers for doing all remaining reps rather than just one": "当重复时，任务工具提示将显示完成所有剩余重复的数字，而不仅仅是一个",
    "Within this menu you can see the effects of your Items on your Skills": "在这个菜单中，你可以看到你的物品对技能的影响",
    "Automatically used Items also cannot be undone": "自动使用的物品也不能撤消",
    "Disabled due to being fully completed": "由于完全完成而禁用",
    "Don't Repeat Tasks": "不要重复任务",
    "Out of Energy": "耗尽能量",
    "Skills gained:": "获得的技能：",
    "Start the Journey Over, Wiser": "重新开始吧，聪明点",
    "The effects of used Items disappear.": "使用过的物品的效果消失。",
    "You keep all your Skills and Perks.": "你保留你所有的技能和特权。",
    "You keep half your Items (rounded up).": "你保留一半的物品（四舍五入）。",
    "You used up all your Energy, but this is not the end.": "你用尽了你所有的能量，但这并不是结束。",
    "You've now done your 1st Energy Reset": "现在你已经完成了第一次能量重置",
    "Unlocked 📖How to Read": "已解锁 📖如何阅读",
    "How to Read": "如何阅读",
    "Improves 🧠Study Task speed by 50%": "提高 🧠学习 任务速度50%",
    "You've now done your 2nd Energy Reset": "现在你已经完成了第二次能量重置",
    "Food": "食物",
    "Can take you above your Max Energy": "能让你超越你的最大能量",
    "Right-click to use all": "右键点击以使用全部",
    "You've now done your 3rd Energy Reset": "现在你已经完成了第三次能量重置",
    "🔨Crafting": "🔨制作",
    "📝Mystery Perk": "📝神秘特权",
    "🏹Arrow Items": "🏹箭物品",
    "⛺Survival": "⛺生存",
    "🗺️Travel": "🗺️旅行",
    "🗺️Travel, ⛺Survival": "🗺️旅行, ⛺生存",
    "Arrow": "箭",
    "Chit-chat": "闲聊",
    "Daydream About Leaving": "梦想着离开",
    "Deal with Drunkards": "对付酒鬼",
    "Fletch Arrows": "造箭",
    "Improves ⚔️Combat Task speed by 15% each": "每个⚔️战斗任务速度提高15%",
    "Learn How to Write": "学习如何写作",
    "Learn Routines": "学习例程",
    "Notice Smoke in the Distance": "注意远处的烟雾",
    "Sparring": "拳击",
    "Zone 2 - The Village Watch": "区域2 -村庄守卫",
    "⚔️Combat Task speed increased 15%": "⚔️战斗 任务速度提高 15%",
    "📖How to Read": "📖如何阅读",
    "Basic": "基础",
    "Dismiss": "关闭",
    "Last Run": "上一轮",
    "Level": "等级",
    "Total Speed": "总速度",
    "Total Perk bonus": "总特权加成",
    "Return to the game": "返回游戏",
    "Export Save": "导出存档",
    "Import Save": "导入存档",
    "Load the game's progress from disk": "从文件加载游戏进度",
    "Open Changelog": "打开更新日志",
    "Save the game's progress to disk": "导出存档为文件",
    "View the full Changelog of Journey to Ascension": "查看完整的《转生之旅》更新日志",
    "Close Settings Menu": "关闭设置菜单",
    "How to Write": "如何写作",
    "Improves ♟️XP gain by 50%": "提高♟️50%的经验值",
    "Unlocked 📝How to Write": "解锁 📝 如何写作",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "⚙": "⚙",
    "♻": "♻",
    "🍲": "🍲",
    "📖": "📖",
    "ℹ": "ℹ",
    "📝": "📝",
    "🏹": "🏹",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "♟️XP: ": "♟️经验值: ",
    "💪Power: ": "💪力量: ",
    "Skills: ": "技能: ",
    "Prestige: ": "声望: ",
    "Speed multiplier: x": "速度乘数: x",
    "🌀Attunement: ": "🌀点化: ",
    "🗡️Subterfuge - Level ": "🗡️诡计 - 等级 ",
    "🧠Study - Level ": "🧠学习 - 等级 ",
    "🔎Search - Level ": "🔎搜搜 - 等级 ",
    "🎭Charisma - Level ": "🎭魅力 - 等级 ",
    "🔨Crafting - Level ": "🔨制作 - 等级 ",
    "⚔️Combat - Level ": "⚔️战斗 - 等级 ",
    "🗺️Travel - Level ": "🗺️旅行 - 等级 ",
    "⛺Survival - Level ": "⛺生存 - 等级 ",
    "🔋Energy - ": "🔋能量 - ",
    "🔨Crafting is now ": "🔨制作 现在是 ",
    "⚔️Combat is now ": "⚔️战斗 现在是 ",
    "🧠Study is now ": "🧠学习 现在是 ",
    "🗺️Travel is now ": "🗺️旅行 现在是 ",
    "🔎Search is now ": "🔎搜索 现在是 ",
    "⛺Survival is now ": "⛺生存 现在是 ",
    "🗡️Subterfuge is now ": "🗡️诡计 现在是 ",
    "🎭Charisma is now ": "🎭魅力 现在是 ",
    "⚔️Combat: ": "⚔️战斗: ",
    "🎭Charisma: ": "🎭魅力: ",
    "🧠Study: ": "🧠学习: ",
    "🔎Search: ": "🔎搜索: ",
    "🗡️Subterfuge: ": "🗡️诡计: ",
    "🔨Crafting: ": "🔨制作: ",
    "⛺Survival: ": "⛺生存: ",
    "🗺️Travel: ": "🗺️旅行: ",
    "Unlocked Skill ": "已解锁技能 ",
    "New highest Zone: ": "新的最高区域：",
    "From level: x": "来自等级: x",
    "From other sources: x": "来自其他来源: x",
    "New highest Zone fully completed: ": "新的完全完成最高区域:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\(\+([\d\.,]+)\)$/,
    /^([\d\.,]+) \(\+([\d\.,]+)\)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) \(x([\d\.]+) speed\)$/, '+$1 (x$2 速度)'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Unlocked in Zone ([\d\.,]+)$/, '解锁于区域 $1'],
    [/^Gives ([\d\.,]+) 🔋Energy each$/, '每个给予 $1 🔋能量'],
    [/^Gained ([\d\.,]+) 🔋Energy$/, '获得 $1 🔋能量'],
    [/^Used ([\d\.,]+) 🍲Food$/, '使用了 $1 🍲食物'],
    [/^Used ([\d\.,]+) 🏹Arrow$/, '使用了 $1 🏹箭'],
    [/^You've now done your ([\d\.,]+)th Energy Reset$/, '现在你已经完成了第 $1 次能量重置'],
    [/^This was your ([\d\.,]+)th Energy Reset$/, '这是你的第 $1 次'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);