/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "⚔️Combat": "⚔️战斗",
    "⏰Seconds": "⏰秒",
    "🧠Study": "🧠学习",
    "🔎Search": "🔎搜索",
    "🔋Energy": "🔋能量",
    "📈Stats": "📈统计",
    "💪Power": "💪力量",
    "Load": "加载",
    "Learn How to Read": "学习如何阅读",
    "Items": "物品",
    "Normal Task": "普通任务",
    "Perks": "特权",
    "Repeat Tasks": "重复任务",
    "Rewards": "奖励",
    "Skill Gains": "技能增益",
    "🎭Charisma": "🎭魅力",
    "Undo": "撤销",
    "Train with Weapons": "武器训练",
    "Controls": "控制",
    "Do Energy Reset": "进行能量重置",
    "End of Content": "内容终点",
    "🌀Attunement": "🌀点化",
    "🗡️Subterfuge": "🗡️诡计",
    "📖Mystery Perk": "📖神秘特权",
    "✨Divine Spark": "✨神圣之火",
    "Artifacts": "神器",
    "Beg for Food": "乞讨食物",
    "Completions": "完成",
    "🔎Search, 🗡️Subterfuge": "🔎搜索, 🗡️诡计",
    "Bonuses not from levels (E.G., from Items and Perks) are not scaled down this way": "不是来自等级的奖励（例如，来自道具和特权）不会按比例减少",
    "Congrats on winning the game. Fow now.": "祝贺你赢得比赛。现在出发。",
    "Cost Estimate": "成本估算",
    "Hide and Seek": "捉迷藏",
    "Join the Watch": "加入守卫",
    "Lorem Ipsum": "Lorem Ipsum",
    "Mandatory Task": "必做任务",
    "Observe Surroundings": "观察周围环境",
    "Read Noticeboard": "阅读布告栏",
    "Skill speed increases 1% per level, while ♟️XP needed to level up increases 2%": "技能速度每升一级增加1%，而♟️升级所需经验增加2%",
    "The speed of Tasks with multiple skills scale by the square or cube root of the skill level bonuses": "多个技能的任务速度由技能等级奖励的平方根或立方根决定",
    "You've reached the end of all content that exists!": "你已经到达了所有存在的内容的尽头！",
    "🍲Food Items": "🍲食物物品",
    "🗺️Move to Zone": "🗺️移动到区域",
    "Bonus": "加成",
    "Item(s)": "物品",
    "No Item to undo": "无物品可撤销",
    "Skill": "技能",
    "Stats": "统计",
    "tasks": "任务",
    "Travel Task": "旅行任务",
    "Undo Last Item Use": "撤销最近使用的物品",
    "🔋Energy goes down over time while you have a Task active": "🔋当你有一个任务处于激活状态时，能量会随着时间的推移而下降",
    "Bonuses to different Task types stack multiplicatively with one another": "不同任务类型的奖励会互相叠加",
    "Current Skill bonuses:": "当前技能奖励：",
    "Disabled until you complete the": "禁用，直到您完成",
    "Disabled until you do your first Energy Reset": "在你进行第一次能量重置之前是不可用的",
    "Item undo is available until you start your next Task": "在开始下一个任务之前，项目撤销是可用的",
    "Items can be used to get bonuses that last until the next Energy Reset": "物品可以用来获得持续到下一次能量重置的奖励",
    "Lets you reopen the last Energy Reset Summary": "让您重新打开上次的能量重置摘要",
    "Lets you Save and Load from disk": "允许您从磁盘保存和加载",
    "Mandatory": "必选",
    "Open Settings Menu": "打开设置菜单",
    "Perks are permanent bonuses with a variety of effects": "津贴是具有多种效果的永久性奖励",
    "Right-click to use all rather than just one": "右键单击可以使用全部而不是一个",
    "The bonuses stack additively; 2 +100% results in 3x speed, not 4x": "加成叠加；2 +100%的速度是3倍，而不是4倍",
    "The bonuses stack multiplicatively; 2 +100% results in 4x speed, not 3x": "奖励以乘法方式堆叠；2 +100%的速度是4倍，而不是3倍",
    "Toggle between repeating Tasks if they have multiple reps, or only doing a single rep": "在重复任务之间切换，如果他们有多个代表，或只做一个代表",
    "Using an Item while already having a Task active will prevent undoing": "在已激活任务的情况下使用项目将阻止撤消",
    "View Last Energy Reset Summary": "查看上次能量重置摘要",
    "When repeating, the Task tooltip will show the numbers for doing all remaining reps rather than just one": "当重复时，任务工具提示将显示完成所有剩余重复的数字，而不仅仅是一个",
    "Within this menu you can see the effects of your Items on your Skills": "在这个菜单中，你可以看到你的物品对技能的影响",
    "Automatically used Items also cannot be undone": "自动使用的物品也不能撤消",
    "Disabled due to being fully completed": "由于完全完成而禁用",
    "Don't Repeat Tasks": "不要重复任务",
    "Out of Energy": "耗尽能量",
    "Skills gained:": "获得的技能：",
    "Start the Journey Over, Wiser": "重新开始吧，聪明点",
    "The effects of used Items disappear.": "使用过的物品的效果消失。",
    "You keep all your Skills and Perks.": "你保留你所有的技能和特权。",
    "You keep half your Items (rounded up).": "你保留一半的物品（四舍五入）。",
    "You used up all your Energy, but this is not the end.": "你用尽了你所有的能量，但这并不是结束。",
    "You've now done your 1st Energy Reset": "现在你已经完成了第一次能量重置",
    "Unlocked 📖How to Read": "已解锁 📖如何阅读",
    "How to Read": "如何阅读",
    "Improves 🧠Study Task speed by 50%": "提高 🧠学习 任务速度50%",
    "You've now done your 2nd Energy Reset": "现在你已经完成了第二次能量重置",
    "Food": "食物",
    "Can take you above your Max Energy": "能让你超越你的最大能量",
    "Right-click to use all": "右键点击以使用全部",
    "You've now done your 3rd Energy Reset": "现在你已经完成了第三次能量重置",
    "🔨Crafting": "🔨制作",
    "📝Mystery Perk": "📝神秘特权",
    "🏹Arrow Items": "🏹箭物品",
    "⛺Survival": "⛺生存",
    "🗺️Travel": "🗺️旅行",
    "🗺️Travel, ⛺Survival": "🗺️旅行, ⛺生存",
    "Arrow": "箭",
    "Chit-chat": "闲聊",
    "Daydream About Leaving": "梦想着离开",
    "Deal with Drunkards": "对付酒鬼",
    "Fletch Arrows": "造箭",
    "Improves ⚔️Combat Task speed by 15% each": "每个⚔️战斗任务速度提高15%",
    "Learn How to Write": "学习如何写作",
    "Learn Routines": "学习例程",
    "Notice Smoke in the Distance": "注意远处的烟雾",
    "Sparring": "拳击",
    "📖How to Read": "📖如何阅读",
    "Basic": "基础",
    "Dismiss": "关闭",
    "Last Run": "上一轮",
    "Level": "等级",
    "Total Speed": "总速度",
    "Total Perk bonus": "总特权加成",
    "Return to the game": "返回游戏",
    "Export Save": "导出存档",
    "Import Save": "导入存档",
    "Load the game's progress from disk": "从文件加载游戏进度",
    "Open Changelog": "打开更新日志",
    "Save the game's progress to disk": "导出存档为文件",
    "View the full Changelog of Journey to Ascension": "查看完整的《转生之旅》更新日志",
    "Close Settings Menu": "关闭设置菜单",
    "How to Write": "如何写作",
    "Improves ♟️XP gain by 50%": "提高♟️50%的经验值",
    "Unlocked 📝How to Write": "解锁 📝 如何写作",
    "💰Coin Items": "💰金币物品",
    "❤️Mystery Perk": "❤️神秘特权",
    "": "",
    "🗡️Subterfuge, 🔎Search": "🗡️诡计, 🔎搜索",
    "⛺Survival, 🔨Crafting": "⛺生存, 🔨制作",
    "🪓Goblin Waraxe Items": "🪓哥布林战斧物品",
    "Boss Task": "Boss任务",
    "Close Changelog": "关闭更新日志",
    "Fight a Goblin": "和哥布林战斗",
    "Enter the Wilderness": "进入荒野",
    "Disabled due to this Boss requiring more than 5x your current 🔋Energy": "该Boss需要当前🔋能量的5倍以上，暂时被禁用无法使用",
    "- Added changelog": "-增加了变更日志",
    "- Added hint about right-clicking to use all items": "-增加了右键使用所有项目的提示",
    "- Added number postfixes beyond T; all the way up To Dc (though currently higher than Qi does not occur)": "-在T之后增加数字后缀；一直到Dc（虽然目前高于Qi没有发生）",
    "- Added vague hint about push runs": "-增加了关于推跑的模糊提示",
    "- Fixed minor incorrect XP calculation after Major Time Compression Perk is unlocked": "-修正次要错误的XP计算后，主要时间压缩Perk解锁",
    "- Fixed two Perks starting their effect twice": "-修复了两个技能的效果开始两次",
    "- Improved tooltip contrast": "-改进提示的对比度",
    "- Increased size of the button to exit the Energy Reset screen": "-增加了退出能量重置屏幕的按钮的大小",
    "- Moved Attunement from Z8 to Z10": "-调整从Z8移动到Z10",
    "- Moved the automation unlock from Z10 to Z4": "-将自动解锁从Z10移动到Z4",
    "- Softened the language on the Energy Reset screen": "-软化了能量重置界面的语言",
    "- Sped up progression in Zones 2 and 7 a little": "-稍微加快了区域2和区域7的进度",
    "- Split Items into two categories; normal Items and Artifacts": "-将项目分成两类；普通物品和神器",
    "- Split out Skill Gains in the Task tooltip from Rewards": "-将任务提示中的技能增益从奖励中分离出来",
    "- Stopped showing Completions in the Task tooltip of single-rep Tasks": "不再在单次重复任务的任务提示中显示完成情况",
    "- Stopped showing XP Mult in the Task tooltip, as it just caused confusion": "不再在任务提示中显示经验值，因为它只会引起混乱",
    "- The Items and Perks info tooltips now show all the active Skill bonuses provided": "-物品和津贴信息工具提示现在显示所有的活动技能奖金提供",
    "First public release of the game": "游戏的首次公开发行",
    "Goblin Warlord": "哥布林战神",
    "Loot the Fallen": "搜刮陨落者",
    "Rescue Villager": "营救村民",
    "Treat Villager Wounds": "治疗村民伤口",
    "Warn Villagers": "警告村民",
    "Coin": "金币",
    "Improves 🎭Charisma Task speed by 15% each": "提高🎭魅力任务速度15%",
    "⏰Ticks": "⏰时间",
    "🎭Charisma Task speed increased 15%": "🎭魅力任务速度提高15%",
    "⚔️Combat Task speed increased 30%": "⚔️战斗任务速度提高30%",
    "Book": "书",
    "Automation": "自动化",
    "Automate Zone": "自动区域",
    "Automate 全部": "自动全部",
    "Auto Use Items": "自动使用物品",
    "Fish": "鱼",
    "🔮Magic": "🔮魔法",
    "🐻Druid": "🐻德鲁伊",
    "Mushroom": "蘑菇",
    "Reagent": "试剂",
    "Zone": "区域",
    "Save the Village": "拯救村庄",
    "Scroll of Haste": "急速卷轴",
    "Mysterious Amulet": "神秘护身符",
    "Sunken Treasure": "沉没的宝藏",
    "Cactus": "仙人掌",
    "🎖️Village Hero": "🎖️村庄英雄",
    "⚓Sunken Treasure": "⚓沉没的宝藏",
    "⚔️Combat, 🔮Magic": "⚔️战斗，🔮魔法",
    "❤️Villager Gratitude": "❤️村民的感谢",
    "🎲Underground Connection": "🎲地下连接",
    "🏯Found Lost Temple": "🏯找到失落的神庙",
    "👣Walk Without Rhythm": "👣无节奏行走",
    "📿Mysterious Amulet": "📿神秘护身符",
    "🦶Experienced Traveler": "🦶经验丰富的旅行者",
    "🛡️Fortitude": "🛡️坚韧",
    "Artifacts are special Items with powerful single-use effects": "神器是具有强大的一次性使用效果的特殊物品",
    "Attunement": "协调",
    "Energetic Spell": "元气法术",
    "Experienced Traveler": "有经验的旅行者",
    "Firemaking Kit": "生火工具",
    "Found Lost Temple": "发现失落的神庙",
    "Goblin Supplies": "哥布林补给",
    "Goblin Waraxe": "哥布林战斧",
    "High Altitude Climbing": "高海拔攀登",
    "Increased by all Tasks it boosts": "它能提高增加了所有的任务",
    "Increased by fighting Bosses": "与首领战斗提升",
    "Increases starting 🔋Energy by 50": "增加起始🔋能量50点",
    "Minor Time Compression": "次要时间压缩",
    "Note that the bonus does not stack if a Task uses more than one of these Skills": "请注意，如果一个任务使用多个这些技能，则奖励不会叠加",
    "Reduces all 🔋Energy consumption 20%": "降低20%的全部🔋能量消耗",
    "Right-click Tasks to designate them as automated": "右键单击任务，将它们指定为自动化的",
    "Sure would be handy to have more than one of these": "要是能有多一个就好了",
    "Tasks reps that are completed instantly (in a single ⏰Tick) now cost 80% less 🔋Energy": "立即完成的任务代表（在一个⏰Tick中）现在消耗的🔋能量减少80%",
    "The effects apply to just a single rep of the next Task started": "这些效果只适用于下一个已启动任务的单个代表",
    "The next Task rep you start is 5x as fast": "你开始的下一个任务代表的速度是原来的5倍",
    "They otherwise behave identically to other Items": "除此之外，它们的行为与其他物品相同",
    "They'll be executed in the order you right-clicked them, as indicated by the number in their corner": "它们将按照你右键点击的顺序被执行，就像它们角落里的数字所显示的那样",
    "Toggle between automating Tasks in the current zone, and not automating": "在自动执行当前区域中的任务和不自动执行任务之间切换",
    "Toggle between automating Ttasks in all zones, and not automating": "在所有区域的任务自动化和不自动化之间切换",
    "Toggle between items being used automatically, and only being used manually": "在自动使用和仅手动使用的项目之间切换",
    "Total Item bonus": "累计道具加成",
    "Travel Equipment": "旅行装备",
    "Underground Connection": "地下连接",
    "Unlocks automatic Item use": "解锁自动使用物品",
    "Unlocks the 🌀Attunement mechanic": "解锁🌀调谐机制",
    "Unlocks Zone Automation": "解锁区域自动化",
    "Village Hero": "村庄英雄",
    "Villager Gratitude": "村民的感谢",
    "Walk Without Rhythm": "无节奏行走",
    "Won't use Artifacts": "不会使用神器",
    "Zones where all Tasks are instant without using Items are completed for free in a single ⏰Tick when doing an 🔋Energy Reset": "在没有使用物品的情况下，所有任务都是即时完成的区域，当做🔋能量重置时，可以在一个⏰Tick中免费完成",
    "🌲Magical Root Items": "🌲魔法根物品",
    "🍄Mushroom Items": "🍄蘑菇类物品",
    "Angry Ent": "愤怒的树人",
    "Befried a Deer": "烤鹿",
    "Build a Fire": "生火",
    "Find an Amulet": "找到一个护身符",
    "Find Cave Entrance": "寻找洞穴入口",
    "Forage for Mushrooms": "采蘑菇",
    "Improves ⛺Survival Task speed by 15% each": "每个⛺生存任务速度提高15%",
    "Look for Tracks": "寻找踪迹",
    "Survive the Night": "熬过黑夜",
    "Close Stats Menu": "关闭统计菜单",
    "Manual Us Items": "手动使用物品",
    "🧥Worm Hide Coat Items": "🧥虫皮大衣物品",
    "🦑Calamari Items": "🦑鱿鱼物品",
    "🦴Oracle Bone Items": "🦴甲骨物品",
    "🐇Scroll of Haste Items": "🐇急速卷轴物品",
    "🔎Search, 🔮Magic": "🔎搜索，🔮魔法",
    "🔎Search, 🗺️Travel": "🔎搜索，🗺️旅行",
    "🔎Search, 🐻Druid": "🔎搜索，🐻德鲁伊",
    "🔎Search, ⛺Survival, 🛡️Fortitude": "🔎搜索, ⛺生存, 🛡️坚韧",
    "🗺️Travel, 🔎Search": "🗺️旅游，🔎搜索",
    "🗺️Travel, 🛡️Fortitude": "🗺️旅游，🛡️坚韧",
    "🔪Bandit Weapon Items": "🔪暗行者武器物品",
    "🔗City Chain Items": "🔗城市链接物品",
    "📦Goblin Supplies Items": "📦哥布林物资物品",
    "🎒Travel Equipment Items": "🎒旅行装备物品",
    "🔥Firemaking Kit Items": "🔥生火工具物品",
    "🌵Cactus Items": "🌵仙人掌物品",
    "🌿Reagent Items": "🌿试剂物品",
    "📚Book Items": "📚书籍物品",
    "🐟Fish Items": "🐟鱼类物品",
    "🐻Druid, 🔎Search": "🐻德鲁伊, 🔎搜索",
    "🐻Druid, 🔮Magic": "🐻德鲁伊, 🔮魔法",
    "🐻Druid, 🎭Charisma": "🐻德鲁伊, 🎭魅力",
    "🔨Crafting, ⛺Survival": "🔨制作, ⛺生存",
    "🔨Crafting, 🔮Magic": "🔨制作, 🔮魔法",
    "🔨Crafting, 🗡️Subterfuge": "🔨制作, 🗡️诡计",
    "Automate 区域": "自动化区域",
    "⚔️Combat, 🛡️Fortitude": "⚔️战斗, 🛡️坚韧",
    "⛺Survival, 🔎Search": "⛺生存, 🔎搜索",
    "⛺Survival, 🛡️Fortitude": "⛺生存, 🛡️坚韧",
    "⛺Survival, 🔎Search, 🗺️Travel": "⛺生存, 🔎搜索, 🗺️旅行",
    "⛺Survival, 🧠Study, 🛡️Fortitude": "⛺生存, 🧠学习, 🛡️坚韧",
    "🧠Study, 🔮Magic": "🧠学习, 🔮魔法",
    "🧠Study, 🔎Search": "🧠学习, 🔎搜索",
    "🧠Study, 🔎Search, ⛺Survival": "🧠学习, 🔎搜索, ⛺生存",
    "🔮Magic, 🧠Study": "🔮魔法, 🧠学习",
    "🗡️Subterfuge, ⛺Survival": "🗡️诡计, ⛺生存",
    "🎭Charisma, 🔎Search": "🎭魅力, 🔎搜索",
    "🎭Charisma, 🗡️Subterfuge": "🎭魅力, 🗡️诡计",
    "🛡️Fortitude, ⛺Survival": "🛡️坚韧, ⛺生存",
    "Avoid Notice by the Sandworm": "避免被沙虫注意",
    "Bandits": "强盗",
    "Bribe the City Guards": "贿赂城市警卫",
    "Build a Hut": "建一间小屋",
    "Build Another Hut": "再建一间小屋",
    "Buy a Book": "买一本书",
    "Cast a Spell": "施法",
    "Catch Fish": "抓鱼",
    "Catch More Fish": "抓更多的鱼",
    "Chat with Travelers": "与旅行者聊天",
    "Comb the Desert": "梳理沙漠",
    "Convince the Magician": "说服魔术师",
    "Corrupt Mayor": "腐败的市长",
    "Create Firemaking Kit": "创建造火工具",
    "Dive as a Squid": "像鱿鱼一样潜水",
    "Do a Favor": "帮个忙",
    "Embark on a Quest": "开始一项任务",
    "Enter the City": "进入城市",
    "Enter the Oasis": "进入绿洲",
    "Explore the Jungle": "探索丛林",
    "Fend for Yourself": "自己照顾自己",
    "Figure Out How to Attune": "弄清楚如何调谐",
    "Find a Way Through": "找到一条出路",
    "Find the Island": "寻找岛屿",
    "Find the Oasis": "寻找绿洲",
    "Gather Reagent": "收集试剂",
    "Get to the City": "进城",
    "Get Used to Traveling": "适应旅行",
    "Giant Sandworm": "巨大沙虫",
    "Give Yourself a Pep Talk": "给自己打气",
    "Go Sightseeing": "去观光",
    "Goblin Chieftain": "哥布林首领",
    "Harvest Cactus": "收获仙人掌",
    "Horde of Lizardfolk": "蜥蜴族",
    "Hunt for the First Reagent": "寻找第一种试剂",
    "Hunt for the Second Reagent": "寻找第二种试剂",
    "Inspect Wall Paintings": "检查壁画",
    "Investigate Rumors of a Magician": "调查关于魔术师的谣言",
    "Join a Caravan": "加入商队",
    "Kraken": "克拉肯",
    "Land on Island": "登陆海岛",
    "Leave Via Back Entrance": "从后门离开",
    "Locate the Mountain": "确定山的位置",
    "Look for Land": "寻找土地",
    "Low-oxygen Exercise": "低氧运动",
    "Make Climbing Gear": "制作攀岩装备",
    "Make Travel Equipment": "制作旅行装备",
    "Meet a Magical Creature": "遇见一个神奇的生物",
    "Negotiate with a Rogue Guard": "与一个流氓守卫谈判",
    "Overcome Mirage": "克服海市蜃楼",
    "Practice Transforming": "实践改造",
    "Practice Traveling Unnoticed": "练习不被注意的旅行",
    "Prepare to Scale the Mountain": "准备攀登这座山",
    "Repair Ship": "修理船",
    "Rescue Captives": "营救人质",
    "Scale the Mountain": "攀登高山",
    "Scout the Cave": "侦察洞穴",
    "Scout the Road Ahead": "侦察前方道路",
    "Scribe Scroll of Haste": "急速卷轴",
    "Search the Archives for Magic": "搜索魔法档案",
    "Skulk About": "鬼鬼祟祟",
    "Spar with the Guards": "与卫兵对打",
    "Steal Some Reagents": "偷一些试剂",
    "Steal Supplies": "偷取物资",
    "Study at the Mage's Guild": "在法师公会学习",
    "Survive a Mugging": "从抢劫中幸存",
    "Talk to the Local Wildlife": "与当地的野生动物交谈",
    "Train for Your Quest": "为你的任务而训练",
    "Try Casting a Spell": "试着施法",
    "Try to Transform Into an Eagle": "试着变成一只鹰",
    "Weather a Storm": "经受风暴",
    "Werewolf": "狼人",
    "Work on Your Tan": "晒黑皮肤",
    "and": "和",
    "Prestige": "声望",
    "Prestige Task": "声望任务",
    "Oracle Bone": "甲骨",
    "Oasis Water": "绿洲水",
    "Manual Use Items": "手动使用物品",
    "💃The Worm": "💃蠕虫",
    "⚖️Purged Bureaucracy": "⚖️清除官僚主义",
    "💀Goblin Scourge": "💀哥布林祸害",
    "🐲Dragon Scale Items": "🐲龙鳞物品",
    "🐲Dragon Scale Item": "🐲龙鳞物品",
    "🛠️Crafting Recipe Items": "🛠️制作配方物品",
    "🛠️Crafting Recipe Item": "🛠️制作配方物品",
    "👢Knightly Boots Items": "👢骑士战靴物品",
    "👢Knightly Boots Item": "👢骑士战靴物品",
    "🕯️Mystic Incense Items": "🕯️神秘香物品",
    "🕯️Mystic Incense Item": "🕯️神秘香物品",
    "🤿Deep Sea Diving": "🤿深海潜水",
    "🙏Ascension": "🙏转生",
    "Apologize for Stealing Reagents": "为偷试剂道歉",
    "Bandit Weapon": "强盗的武器",
    "Begin Search for the Next Ritual": "开始寻找下一个仪式",
    "Calamari": "鱿鱼",
    "City Chain": "城市链",
    "Deep Sea Diving": "深海潜水",
    "Djinn Lamp": "神灵灯",
    "Energetic Memory": "精力充沛的记忆",
    "Go for a Walk": "出去散步",
    "Goblin Scourge": "妖精祸害",
    "Goblin Treasure": "妖精宝藏",
    "Guided Spellcasting": "引导施法",
    "Improves ⚔️Combat and 🛡️Fortitude Task speed by 30%": "提高⚔️战斗和🛡️坚韧任务速度30%",
    "Improves ⛺Survival Task speed by 10% each": "提高⛺生存任务速度各10%",
    "Improves ⛺Survival, 🔮Magic, and 🐻Druid Task speed by 10% each": "提高⛺生存，🔮魔法和🐻德鲁伊任务速度各10%",
    "Improves 🎭Charisma and ⛺Survival Task speed by 20% each": "提高🎭魅力和⛺生存任务速度各20%",
    "Improves 🎭Charisma and 🔨Crafting Task speed by 30%": "提高🎭魅力和🔨锻造速度30%",
    "Improves 🎭Charisma and 🗡️Subterfuge Task speed by 50% each": "提高🎭魅力和️诡计任务速度各50%",
    "Improves 🔎Search and 🐻Druid Task speed by 20% each": "提高🔎搜索和🐻德鲁伊任务速度各20%",
    "Improves 🔎Search and 🐻Druid Task speed by 30%": "提高🔎搜索和🐻德鲁伊任务速度30%",
    "Improves 🗡️Subterfuge and ⛺Survival Task speed by 50% each": "提高🗡️诡计和⛺生存任务速度各50%",
    "Improves 🙏Ascension and 🔮Magic Task speed by 30% each": "提高🙏转生和🔮魔法任务速度各30%",
    "Improves 🙏Ascension Task speed by 10% each": "🙏转生任务速度各提升10%",
    "Improves 🛡️Fortitude Task speed by 100% each": "提高🛡️坚韧任务速度100%",
    "In each Zone 🔋Energy consumption is reduced 5% compounding for each Zone you've reached past it": "在每个区域🔋能源消耗减少5%复合为每一个区域，你已经达到它",
    "Infuse Mystic Incense": "注入神秘的香",
    "Magical Root": "魔法根",
    "Mystic Incense": "神秘香",
    "On each Energy Reset, increase max 🔋Energy by the current Zone / 10": "每次能量重置，增加当前区域的最大🔋能量/ 10",
    "Practice Memorization": "实践记忆",
    "Purged Bureaucracy": "清除官僚主义",
    "Reduce 🔋Energy drain based on the highest Zone reached": "根据达到的最高区域减少🔋能量消耗",
    "Reflections on the Journey": "旅途感悟",
    "Rest for a While": "休息一会儿",
    "So Zone 12 has 🔋Energy cost multiplied by 0.95^2 if the highest Zone reached is 14": "因此，如果达到的最高区域是14，那么区域12的能量成本乘以0.95^2🔋",
    "So Zone 9 gives 0.9 max 🔋Energy": "所以9区提供0.9最大🔋能量",
    "The Worm": "蠕虫",
    "Touch the Divine": "触摸神圣",
    "Werewolf Fur": "狼人皮毛",
    "Within this menu you can Prestige to gain ✨Divine Spark, and buy powerful upgrades": "在这个菜单中，你可以声望获得✨神圣火花，并购买强大的升级",
    "Worm Hide Coat": "虫皮大衣",
    "Max 🔋Energy: +1.5 (Energetic Memory Perk)": "最大🔋能量：+1.5（能量记忆特权）",
    "🐇Haste": "🐇急速",
    "🐇Haste*": "🐇急速*",
    "Modifiers": "修饰符",
    "Next 1 Task reps are 5x as fast": "接下来1个任务的速度是原来的5倍",
    "Undid use of 1 🐇Scroll of Haste": "取消使用1🐇急速卷轴",
    "Undo Use of 1 Scroll of Haste": "取消1急速卷轴的使用",
    "Used 1 🐇Scroll of Haste": "使用1🐇急速卷轴",
    "🐺Werewolf Fur Items": "🐺狼人皮毛物品",
    "💧Oasis Water Items": "💧绿洲水",
    "🧞Djinn Lamp Items": "🧞精灵之灯物品",
    "🧞Djinn Lamp Item": "🧞精灵之灯物品",
    "🧠Study, 🎭Charisma": "🧠学习，🎭魅力",
    "🧠Study, 🗡️Subterfuge": "🧠学习，🗡️诡计",
    "Banish Evil Spirit": "驱除邪灵",
    "Bottle Oasis Water": "瓶装绿洲水",
    "Explore Kraken's Lair": "探索海妖的巢穴",
    "Find More Lamps": "找到更多的灯",
    "Frolic in the Water": "在水里嬉戏",
    "Gather Second Reagent": "收集第二试剂",
    "Gather Shed Fur from Lair": "从巢穴收集脱落的皮毛",
    "Learn to Dance the Worm": "学会跳蠕虫舞",
    "Prepare for the Journey Ahead": "为未来的旅程做好准备",
    "Purge Corrupt Bureacracy": "清除腐败的官僚机构",
    "Reflect on the Journey": "反思旅程",
    "Return to the Magician": "回到魔术师身边",
    "Sleepy Djinn": "沉睡的神灵",
    "Steal Their Oracle Bones": "偷他们的甲骨",
    "* Haste will only apply to the first 1 reps": "* 急速效果仅前1次生效",
    "Awakening": "觉醒",
    "🏔️Dragon Killing Plan": "🏔️屠龙计划",
    "🐉Dragon Slayer": "🐉屠龙者",
    "👥Hide in Plain Sight": "👥藏在众目睽睽之下",
    "🔷Dream Prism": "🔷梦想棱镜",
    "🧙‍♂️Headmaster": "🧙‍♂️校长",
    "🧱Tower of Babel": "🧱巴别塔",
    "Cave Insect": "洞穴昆虫",
    "Crafting Recipe": "制作配方",
    "Creates a copy of every Item type you've obtained this Energy Reset (except Dreamcatchers)": "复制你获得能量重置的每个物品类型（捕梦网除外）",
    "Dragon Killing Plan": "屠龙计划",
    "Dragon Scale": "龙鳞",
    "Dragon Slayer": "屠龙者",
    "Dream Prism": "梦想棱镜",
    "Dreamcatcher": "追梦人",
    "Each Zone fully completed in this Prestige increases Task Speed 2%": "每完成一个区域，任务速度增加2%",
    "For instance, having fully completed the 15th Zone would speed up Task speed 1.02^15 = 35%": "例如，完全完成第15个区域将使任务速度提高1.02^15 = 35%",
    "Headmaster": "校长",
    "Hide in Plain Sight": "隐藏在众目睽睽之下",
    "Improves ✨Divine Spark gain by 33%": "提高✨神圣火花33%的增益",
    "In each Zone 🔋Energy consumption is reduced 10% compounding for each Zone you've reached past it": "在每个区域🔋能源消耗减少10%复合为每一个区域，你已经达到它",
    "Knightly Boots": "骑士的靴子",
    "Magic Ring": "魔法戒指",
    "Magical Essence": "魔法精华",
    "Magical Vessel": "魔法容器",
    "Major Time Compression": "主要时间压缩",
    "Note that it's based on your highest fully completed, so you can skip fully completing earlier Zones if you want": "请注意，它是基于你的最高完全完成，所以你可以跳过完全完成较早的区域，如果你想",
    "Reduces the real-world time for non-instant Tasks by 50% (does not affect 🔋Energy use)": "将非即时任务的实际时间减少50%（不影响🔋能源使用）",
    "So Zone 12 has 🔋Energy cost multiplied by 0.9^2 if the highest Zone reached is 14": "因此，如果达到的最高区域是14，则区域12的能量成本乘以0.9^2🔋",
    "Squared after Zone 10, so Zone 20 gives 2 * 2 = 4 max 🔋Energy": "在区域10之后平方，所以区域20给出2 * 2 = 4最大🔋能量",
    "Tasks with instant reps now complete the whole Task in a single ⏰Tick, rather than a single ⏰Tick per rep": "具有即时代表的任务现在在一个⏰Tick中完成整个任务，而不是每个代表一个⏰Tick",
    "The next Task rep you start gives 3x as much XP": "你开始的下一个任务代表将获得3倍的经验",
    "This also means the 🔋Energy cost is that of a single ⏰Tick": "这也意味着🔋能量消耗是单个⏰Tick的能量消耗",
    "Tower of Babel": "巴别塔",
    "Unified Theory of Magic": "统一魔法理论",
    "Wake Up": "醒来",
    "🧠Study, 🔨Crafting": "🧠学习, 🔨制作",
    "🦟Cave Insect Items": "🦟洞穴昆虫物品",
    "🗡️Subterfuge, 🧠Study": "🗡️诡计, 🧠学习",
    "🔮Magic, 🎭Charisma": "🔮魔法, 🎭魅力",
    "🏺Magical Vessel Items": "🏺魔法容器物品",
    "🙏Ascension, 🛡️Fortitude": "🙏转生, 🛡️坚韧",
    "⚔️Combat, 🔎Search": "⚔️战斗, 🔎搜索",
    "Dragon": "龙",
    "Dragon Spawn": "巨龙出生",
    "Gather Dragon Scales": "采集龙鳞",
    "Gather Essence": "采集精华",
    "Apotheosize": "神化",
    "Become Honorary Headmaster": "成为名誉校长",
    "Build Giant Tower": "建造巨塔",
    "Catch Some Insects for Later": "抓一些昆虫待会再吃",
    "Contain the Dream": "包容梦境",
    "Discover Your True Shape": "发现真实的自己",
    "Enter the Dragon's Lair": "进入龙穴",
    "Evade the Dragon": "躲避巨龙",
    "Figure Out the Next Ritual": "找出下一个仪式",
    "Figure Out Where to Go Next": "弄清楚下一步要去哪里",
    "Find the Hidden Entrance": "找到隐藏的入口",
    "Gather Your Thoughts": "收集你的想法",
    "Go on a Long Trek": "进行一次长途跋涉",
    "Go to a Place of Power": "去一个有权力的地方",
    "Grab the Reagent You Need": "抓住你需要的试剂",
    "Hide from the Dragon": "躲避恶龙",
    "Hide from the Dragon Some More": "再躲避一下巨龙",
    "Hunt Down the Dragon's Spawn": "追捕龙之卵",
    "Imbue Magical Vessel": "注入魔法容器",
    "Improve Your Time Compression": "改善你的时间压缩",
    "Invent a New Spell": "发明一个新的法术",
    "Journey Beyond": "超越之旅",
    "Live Off of Cave Critters": "以洞穴生物为食",
    "Loot Dragon's Victims": "战利品龙的受害者",
    "Mage's Guild Headmaster": "法师公会会长",
    "Max 🔋Energy: +4.0 (Energetic Memory Perk)": "最大🔋能量：+4.0（能量记忆特权）",
    "Notice Signs You're in a Dream": "注意你在做梦的迹象",
    "Plan How to Kill the Dragon": "计划如何杀死龙",
    "Practice in the Fighting Pits": "在斗牛场练习",
    "Practice Magic Under Pressure": "在压力下练习魔术",
    "Prepare for a Greater Journey": "为更伟大的旅程做好准备",
    "Reflect on Past Obstacles": "反思过去的障碍",
    "Search for the Dragon's Hoard": "寻找龙的宝藏",
    "Study at the Artificer Guild": "在技工协会学习",
    "Talk to Mysterious Being": "与神秘生物交谈",
    "The Weaver of Dreams": "织梦者",
    "Transcend Humanity": "超越人性",
    "Travel the Plains": "平原之旅",
    "Try to Turn into a Dragon": "试着变成一条龙",
    "Write Down Crafting Recipes": "写下制作配方",
    "Auto Tooltips": "自动工具提示",
    "Credits": "鸣谢",
    "Reset Save": "重置存档",
    "Thank you for playing Journey to Ascension!": "感谢您玩“转生之旅”游戏！",
    "You have at last claimed your place among the Gods in Heaven": "你终于在天堂的众神中占有了一席之地",
    "Deal with saving and tooltips, or view the Changelog and Credits": "处理保存和提示信息，或者查看更新记录和鸣谢",
    "Open Credits": "打开 鸣谢",
    "Resets *everything*": "重置 *所有内容*",
    "Switch to Automatic Tooltips": "切换到自动提示信息模式",
    "View the game credits": "查看游戏鸣谢信息",
    "With Manual Tooltips enabled, tooltips only show up while CTRL is held": "在启用手动提示信息的情况下，提示信息仅在按住 CTRL 的时候才会显示出来",
    "Current Zone": "当前区域",
    "To": "到",
    "Task Automation": "任务自动化",
    "Hotkey:": "快捷键:",
    "Automate 当前区域": "自动化 当前区域",
    "Camping Equipment": "露营装备",
    "Effect in current Zone: 30% reduction": "当前区域效果：降低 30%",
    "Improves 🎭Charisma and 🛡️Fortitude Task speed by 20% each": "提升 🎭魅力值和 ??️坚韧性任务完成速度各 20%",
    "Improves 🔎Search and 🔮Magic Task speed by 20% each": "提升 🔎搜寻和 🔮魔法任务完成速度各 20%",
    "Improves 🔎Search and 🔮Magic Task speed by 30%": "提升 🔎搜寻和 🔮魔法任务完成速度 30%",
    "Improves 🔎Search and 🛡️Fortitude Task speed by 30%": "提升 🔎搜寻和 🛡️坚韧性任务完成速度各 30%",
    "Improves 🗡️Subterfuge and 🔮Magic Task speed by 50% each": "提升 🗡️诡计和 ??魔法任务完成速度各 50%",
    "Improves 🗺️Travel and 🛡️Fortitude Task speed by 10% each": "提升 🗺️旅行和 ??️坚韧性任务完成速度各 10%",
    "Improves 🧠Study and 🔮Magic Task speed by 10% each": "提升 🧠研究和 🔮魔法任务完成速度各 10%",
    "Improves 🙏Ascension and 🗺️Travel Task speed by 10% each": "提升 🙏晋升和 🗺️旅行任务完成速度各 10%",
    "Improves 🛡️Fortitude Task speed by 10% each": "提升 🛡️坚韧性任务完成速度各 10%",
    "Improves 🛡️Fortitude Task speed by 15% each": "提升 🛡️坚韧性任务完成速度各 15%",
    "Improves 🛡️Fortitude Task speed by 20% each": "提升 🛡️坚韧性任务完成速度各 20%",
    "Specify Target Zone": "指定目标区域",
    "That includes keeping half after 🔋Energy resets": "这包括在 🔋能量重置后保留一半的效果",
    "The Zone you specify here will be used by the 'To Zone' automation": "您在此处指定的区域将被“至区域”自动化功能所使用",
    "This gives all the benefits doing those Tasks manually would have": "这会提供手动执行这些任务所具有的所有好处",
    "Toggle between no automation, and automating Tasks until the specified Zone (99) is reached": "在无自动化和自动执行任务直至达到指定区域（99）之间切换",
    "Toggle between no automation, automating Tasks in the current zone": "在当前区域自动执行任务之间切换",
    "- Renamed the 'All' task automation mode to 'Until Zone'. You can now specify a Zone that it'll stop when you get to. If you're already in or past that Zone when enabling Until Zone, it'll just do whatever Zone you're in, like Current Zone automation": "- 将“所有”任务自动化模式重命名为“直到区域”现在您可以指定一个区域，在您到达该区域时系统会停止运行。如果在启用“直至区域”功能时您已经处于或已经超过了该区域，那么系统将按照您当前所在的区域进行操作，比如“当前区域自动化”模式。",
    "- The stats screen now shows your Highest Zone reached, and fully completed. If you've Prestiged, it also shows the highest in any Prestige. Note that this number will initially be wrong in saves before this update, since this info was not tracked until now": "- 统计屏幕现在显示你的最高区域达到，并完全完成。如果您已获得荣耀徽章，该页面还会显示您在任何荣耀等级中的最高成就。请注意，此数字在此次更新之前的存档中可能会有误，因为在此之前并未对相关数据进行记录。",
    "- Added a 3rd mandatory Task to Zone 20": "- 在区域 20 中新增了第三个必做任务",
    "- Added a mention to the Energy tooltip that drain is proportional to the time spent on a Task, and goes up a little with each Zone": "- 在能量提示信息中添加了说明，即消耗量与完成任务所花费的时间成正比，并且随着区域的增加而略有增加",
    "- Added a new Prestige repeatable upgrade": "- 新增了一个可重复升级的荣耀奖励",
    "- Added a Save Reset button in the Settings": "- 在设置中添加了保存重置按钮",
    "- Added a setting that makes tooltips only show while CTRL is held (off by default)": "- 默认情况下，设置了只有在按住 CTRL 的情况下才会显示提示信息的选项",
    "- Added a Task after the Z24 Boss": "- 在 Z24 帝王之后新增了一个任务",
    "- Added Credits section": "- 新增了“荣誉”部分",
    "- Added favicon (browser tab icon)": "- 添加了网站图标（浏览器标签页图标）",
    "- Added hotkeys for Automation and Task Repetition": "- 新增了自动化和任务重复的快捷键",
    "- Added two new Prestige unlockables": "- 新增了两个荣耀解锁奖励",
    "- Added Z26 and Z27 bosses and boss Tasks": "- 新增了 Z26 和 Z27 的帝王以及帝王任务",
    "- Added zones Z21 through Z25, including:": "- 新增了 Z21 至 Z25 的区域，包括：",
    "- Added zones Z26 and Z27, including:": "- 新增了 Z26 和 Z27 的区域，包括：",
    "- Added zones Z28, Z29, and Z30, including:": "- 新增了 Z28、Z29 和 Z30 的区域，包括：",
    "- Boss Task automations now get removed on Prestige, since you generally only want to deal with them later in the Prestige run": "- 荣耀奖励中的帝王任务现在在荣耀升级时会自动删除，因为通常您只想在荣耀运行的后期处理这些任务",
    "- Boss Tasks disabled due to costing too much Energy now have a 🚫 icon": "- 因消耗过多能量而被禁用的帝王任务现在会有一个 🚫 图标",
    "- Buffed Divine Speed slightly": "-略微增强神圣速度",
    "- Buffed Magical Essence a bit": "-增强了魔法精华",
    "- Clarified a couple of tooltips": "- 清晰说明了几个提示信息",
    "- Divine Lightning current effect now has three significant figures in the tooltip": "- 神圣闪电当前效果的提示信息现在在其中显示了三位有效数字",
    "- Fixed Bottled Lightning queued stacks not getting zeroed on Energy reset": "修复了瓶装闪电队列在能量重置时不会归零的问题",
    "- Fixed Bottled Lightning showing up in the tooltips of Tasks it doesn't apply to": "-修复了瓶装闪电显示在任务的工具提示中，它不适用",
    "- Fixed buttons getting highlighted in some cases when selected": "- 修复了在某些情况下选中按钮时会出现高亮显示的问题",
    "- Fixed Energy Items energy gain not being truncated at and above Divine Appetite level 7 (showing E.G., 12.00000000002)": "- 修复了能量物品的能量获取在神之食欲等级达到 7 之后不会截断（显示例如 12.00000000002）",
    "- Fixed numbers getting sometimes shown as 1000k and similar rather than 1.00M": "- 修复了有时数字会显示为 1000k 以及类似形式，而不是 1.00M",
    "- Fixed running out of Energy while viewing info from the last Run not giving the Run Over screen": "- 修复了在查看最近一次运行的信息时，能量耗尽不会显示“运行结束”屏幕的问题",
    "- Fixed Task Automation not applying the effects of Haste and similar": "- 修复了任务自动化没有应用加速等效果的问题",
    "- Fixed the 2026 changelog entries saying 2025": "- 修复了 2026 年的更新日志条目显示为 2025 年的问题",
    "- Fixed the Automation mode not getting highlighted any more": "- 修复了自动化模式不再有高亮显示的问题",
    "- Fixed the Dream Prism perk stating its effect twice": "- 修复了“梦幻棱镜”加成条目重复说明其效果的问题",
    "- Fixed the Fully Attuned unlockable referring to the Divine Knowledge unlockable by the wrong name": "- 修复了“完全调谐”解锁项使用错误名称引用神知识解锁项的问题",
    "- Fixed the Items Skill bonus breakdown showing all bonuses as 100 percentage points higher than reality": "- 修复了“物品技能”加成明细将所有加成都显示为比实际值高出 100 个百分点的问题",
    "- Fixed the Perks Skill bonuses breakdown saying 'Item(s)' rather than 'Perk(s)": "- 修复了“加成技能”加成明细中说“物品”而不是“加成”的问题",
    "- Fixed the Prestige Task button not being highlighted in one case where it should be": "- 修复了“荣耀任务”按钮在某些情况下没有高亮显示的问题（而实际上应该高亮显示）",
    "- Fixed the Repeat Tasks and Manual Use Items tooltips not updating on click": "- 修复了重复任务和手动使用物品的工具提示在点击时没有更新的问题",
    "- Fixed the stylesheet being broken": "-修复了样式表被打破",
    "- Fixed the tooltip of Energy Items not updating immediately when you upgrade Divine Appetite": "修复了神之食欲升级时，能量类道具提示没有立即更新的问题",
    "- Fixed the Unified Theory of Magic not always updating the Highest Zone fully completed": "- 修复了“魔法统一理论”无法完全显示最高区域已完成状态的问题",
    "- If the player doesn't figure out prep runs themselves, a hint gets shown a while after unlocking keeping some Items on death": "- 如果玩家自己没有规划好准备行动，解锁后一段时间后会显示提示信息，保留一些物品并在死亡时使用",
    "- If you don't have enough Energy to fully complete a Task, it'll now show the Skill Gains as a range (from how much you'd gain using your current Energy, to fully completing)": "- 如果你没有足够的能量来完全完成一项任务，现在技能收益会显示为一个范围（从使用当前能量所能获得的收益，到完全完成）",
    "- If you get far enough without beating any Bosses, the game now reminds you of their existence": "- 如果你没有击败任何首领，游戏现在会提醒你他们的存在",
    "- Increased the Magic Ring boost from 3x to 5x": "- 将魔法戒指的加成从 3 倍提高到 5 倍",
    "- Made Defy the Gods task about 30% easier": "- 将“挑战众神”任务的难度降低约 30%",
    "- Made Divine Knowledge's cost scale slightly faster": "- 将“神圣知识”的成本曲线略微加快",
    "- Made Divine Lightning scale faster in cost": "- 将“神圣闪电”的成本曲线加快",
    "- Made it extra clear that Minor Time Compression's Zone skipping gives all the benefits manually doing the Zone would've": "- 更明确地表明“轻微时间压缩”的区域跳过能带来与手动完成该区域相同的全部好处",
    "- Made Magical Roots give twice as much Fortitude": "- 将“魔法根”的坚韧性加成提高一倍",
    "- Made Permanent Automation and Divine Inspiration have a small cost": "- 将“永久自动化”和“神圣灵感”的成本设置为较小的数值",
    "- Made the bosses in Zone 19 and 20 harder": "- 提高了第 19 区和第 20 区的首领难度",
    "- Made the Changelog box wider": "- 扩宽了变更日志框的宽度",
    "- Made the Fortitude task in Z15 give a bit more XP": "让Z15的刚毅任务给了更多的经验",
    "- Made the post-boss Task in Zone 19 harder": "-增加了19区boss后的任务难度",
    "- Made Transcendant Aptitude cheaper, but made the cost scale up faster": "- 提高了第 19 区的Boss战后的任务难度- 降低了“超越天赋”的价格，但使成本的增长速度加快了",
    "- Made Z23 post-boss task cheaper": "- 降低了“Z23 后期任务”的价格",
    "- Mastery of Time can now skip zones on prestige": "- 现在精通时间技能可以在荣耀状态下跳过区域",
    "- Merged the Druid skill into the Magic skill": "- 将德鲁伊技能合并到了魔法技能中",
    "- Minor Time Compression's tooltip now does the math for how big the effect currently is": "- 修正了“时间压缩”提示栏的描述，现在会显示当前效果的大小",
    "- Now showing highest Zone fully completed in the Unified Theory of Magic Perk": "- 现在在“统一魔法理论”天赋中显示了最高完全完成的区域",
    "- Once keeping some Items on reset is unlocked, the Energy reset lets you decide whether to auto-use Items or not": "- 一旦解锁了在重置时保留某些物品的功能，能量重置就会让你决定是否自动使用物品",
    "- Power gain now gets formated as `1.23k` and such once it passes 1k": "- 力量获取现在会格式化为“1.23k”等，一旦超过 1k 就会如此",
    "- Rebalanced Divine Spark gain entirely, as well as Prestige upgrade costs": "- 重新平衡了神圣火花的获取、荣耀升级成本",
    "- Rebalanced Prestige rewards and upgrade costs": "- 重新平衡了荣耀奖励和升级成本",
    "- Rebalanced some Items": "- 重新平衡了一些物品",
    "- Rebalanced Tasks past Zone 15": "- 重新平衡了第 15 区之后的任务",
    "- Rebalanced the game up to Zone 15": "- 重新平衡了游戏到第 15 区的状况",
    "- Rebalanced the mandatory tasks in Z25": "- 重新平衡了 Z25 中的强制任务",
    "- Reduced the cost of some of the first Prestige upgrades": "- 降低了部分初始荣耀升级的成本",
    "- Reduced the effect of Major Time Compression on Task real-time speed": "- 降低了重大时间压缩对任务实时速度的影响",
    "- Removed the Survival skill. Replaced with Search, Fortitude, Crafting, or nothing depending on the Task": "- 删除了生存技能。取代搜索，坚韧，锻造，或什么都没有取决于任务",
    "- Renamed Firemaking Kit to Camping Equipment and changed its icon": "-重命名生火装备露营装备和改变它的图标",
    "- Setting the automation target Zone to the current Zone or lower now stops ongoing automation": "- 将“炼金工具包”更名为“露营装备”，并更改了其图标- 将自动化目标区域设置为当前区域或更低区域后，当前正在进行的自动化操作将停止。",
    "- Tasks giving an Artifact you've never gotten before now glow": "- 提供了您从未获得过的工件的任务现在会发光。",
    "- The Divine Lightning tooltip now tells you its effect in the highest Zone you've reached": "- 神圣闪电提示信息现在会告知您其效果所在的您所达到的最高区域。",
    "- The Energized prestige upgrade now also boosts Energetic Memory's bonus a little": "- 充能的声望升级现在还会略微提升“能量记忆”的加成效果。",
    "- The game is now content complete": "- 游戏现已完成所有内容。",
    "- The Prestige button no longer shows Divine Spark gain if you can't Prestige yet, instead showing just your current amount. Still clickable": "- “荣耀”按钮在您尚未达到荣耀等级时不再显示神圣火花的获取量，而是仅显示当前的获取量。但该按钮仍然可点击。",
    "- The Prestige button now glows when you reach a new highest Zone, since that at least doubles the Divine Spark gain": "- “荣耀”按钮现在在您达到新的最高区域时会发光，因为这至少会使神圣火花的获取量翻倍。",
    "- The Reflections on the Journey Perk's tooltip now states the highest Zone reached, and the effect in the current Zone": "- “旅途中的反射”强化技能的提示信息现在会显示所达到的最高区域以及当前区域的效果。",
    "- The To Zone automation button is now disabled if the target Zone isn't higher than the current Zone": "- “前往区域”自动化按钮现在如果目标区域不高于当前区域则会处于禁用状态。",
    "- The Z25 Prestige task is now 4 reps instead of 5, slightly higher cost per rep": "- Z25 荣耀任务现在需要完成 4 次，而不是 5 次，每次任务的成本略有提高。",
    "- Updated the tooltip for the Settings Menu button": "- 更新了“设置菜单”按钮的提示信息。",
    "- You no longer keep half your Items on Energy reset; this is unlocked later instead": "- 重新设计了“能量重置”时不会保留一半物品的提示信息；此提示信息将在之后解锁。",
    "- You now get the option to Prestige when you reach the end of content": "- 现在在内容结束时达到荣耀等级时您会有机会进行荣耀升级。",
    "Will reset": "将会重置",
    "Unlockables": "可解锁",
    " gain formula:": " 增益公式:",
    " Gain": " 增益",
    "-- A new Artifact": "——一个新神器",
    "100, multiplied by 2.00 for each Zone past 15": "100，每超过15个区域乘以2.00",
    "Boosts its base from 0.95 to 0.9": "将其基数从0.95提高到0.9",
    "Divine Appetite": "神圣欲望",
    "Divine Inspiration": "神圣灵感",
    "Divine Knowledge": "神圣知识",
    "Divinity": "神圣之力",
    "Do Prestige Reset": "重置职业技能",
    "Doubles 💪Power gain": "双倍💪功率增益",
    "everything": "一切",
    "except that which is granted by Divinity purchases, but gives ✨Divine Spark in return": "除了神性所给予的购买，但给予✨神性火花作为回报",
    "Fully Attuned": "完全契合",
    "Gotta Go Fast": "必须快速行动",
    "Increases ♟️XP gain by 50%": "增加♟️50%经验值增加",
    "Increases ♟️XP gain by 50% and 🌀Attunement gain by 100%": "♟️XP增益50%和🌀调谐增益100%",
    "Increases 🔋Energy gained from Items by 20%": "使 🔋从物品中获得的能量增加 20%",
    "Look in the Mirror": "照镜子查看",
    "Makes 🌀Attunement apply to 🔎Search": "使 🌀契合度适用于 🔎搜索",
    "Makes the Divine Knowledge Prestige upgrade apply to 🌀Attunement": "使神之知识传奇升级适用于 🌀契合度",
    "Note that 🌀Attunement still needs to be unlocked in Zone 10": "请注意， 🌀契合度仍需在第 10 区解锁",
    "Permanent Automation": "永久自动化",
    "Permanently unlocks the 🌀Attunement Perk": "永久解锁 🌀契合度技能",
    "Permanently unlocks the 📿Mysterious Amulet Perk": "永久解锁 📿神秘圣物技能",
    "Permanently unlocks the 🕰️Reflections on the Journey Perk": "永久解锁 🕰️旅途中的映像技能",
    "Repeatable Upgrades": "可重复升级",
    "Unlimited Power": "无限力量",
    "* Skill gain as range since you're expected to run out of 🔋Energy before fully completing this Task": "* 技能收益为区间值，因为预计在完成该任务前，你的🔋能量就会耗尽",
    "🔁Mystery Perk": "🔁 神秘特权",
    "🔎Search, 🛡️Fortitude": "🔎 搜索、🛡️ 坚韧",
    "🔗City Chain Item": "🔗 城邦链道具",
    "🚫Angry Ent": "🚫 暴怒树精",
    "🚫Bandits": "🚫 强盗",
    "🚫Corrupt Mayor": "🚫 腐败市长",
    "🚫Goblin Chieftain": "🚫 哥布林酋长",
    "🛡️Fortitude, 🔨Crafting": "🛡️ 坚韧，🔨 制作",
    "Befriend a Deer": "驯服一只小鹿",
    "Reset, With Auto Use Items": "重置，自动使用道具",
    "Reset, Without Auto Use Items": "重置，不自动使用道具",
    "Skill Gains*": "技能收益*",
    "Study the Amulet": "研究护身符",
    "Unlocked ⌚Minor Time Compression": "已解锁 ⌚小型时间压缩",
    "You lose your unused Items.": "你失去了所有未使用的道具",
    "You've now done your 62nd Energy Reset": "你已完成第62次能量重置",
    "🐇Scroll of Haste Item": "🐇急速卷轴 道具",
    "💰Coin Item": "💰硬币 道具",
    "🗻High Altitude Climbing Perk": "🗻高海拔攀登 特性",
    "🧠Study, 🛡️Fortitude": "🧠学识、🛡️坚韧",
    "🪓Goblin Waraxe Item": "🪓哥布林战斧 道具",
    "🚫Werewolf": "🚫狼人",
    "Drain is proportional to the time spent on a Task. The drain per unit time increases slightly per Zone": "消耗与任务耗时成正比，每进入一个区域，单位时间消耗会小幅提升",
    "Make Camping Equipment": "制作露营装备",
    "Pause on Block": "被阻塞时暂停",
    "Switch to Skip on Blocked Tasks": "切换至“跳过”模式处理被阻塞的任务",
    "This is Zone 1 of 30": "",
    "When using Task Autmation, this setting decides what to do if the next queued Task is blocked (E.G., too strong a Boss). Will either pause the automation, or keep running automated with the Task skipped": "在使用任务自动化功能时，此设置决定了当下一个排队任务被阻塞（例如，遇到过于强大的对手）时应采取何种措施。它可以选择暂停自动化流程，或者继续执行自动化操作但跳过该任务。",
    "Increases 🔮Magic, 🧠Study, and 🔎Search speed by 75%": "提高 🧬魔法、🧠学习和 🔎搜索速度 75%",
    "Reduces the real-world time for non-instant Tasks by 33% (does not affect 🔋Energy use)": "非即时任务在现实世界中的时间减少 33%（不影响 🔋能量使用）",
    "The next Task rep you start gives 5x as much XP": "下次开始的任务会给予 5 倍的经验值",
    "This means you can use more Items in a run than just those gained in that specific run": "这意味着您在一次运行中可以使用比仅在该特定运行中获得的更多的物品",
    "Toggle between no automation, and automating Tasks until the specified Zone (21) is reached": "在不自动操作和自动操作任务直至达到指定区域（21）之间切换",
    "Understanding of the Reset": "关于重置的理解",
    "When you run out of 🔋Energy and reincarnate you keep half your remaining Items (rounded up)": "当您耗尽 🔋能量并重生时，您会保留剩余物品的一半（向上取整）",
    "⚡️Energetic Spell Perk": "⚡️能量法术特权",
    "❤️Villager Gratitude Perk": "❤️村民感恩福利",
    "🎲Underground Connection Perk": "🎲地下连接特权",
    "💎Goblin Treasure Item": "💎哥布林宝藏物品",
    "🔁Understanding of the Reset Perk": "🔁理解重置福利",
    "🔪Bandit Weapon Item": "🔪暗行者武器道具",
    "🦶Experienced Traveler Perk": "🦶资深旅行者福利",
    "🚫Goblin Warlord": "🚫哥布林战神",
    "Increases 🔮Magic, 🧠Study, and 🔎Search speed by 827%": "使 🔮魔法、🧠学习和 🔎搜索速度提高 827%",
    "Unlocked ⚡️Energetic Spell": "解锁⚡️能量法术",
    "Unlocked ❤️Villager Gratitude": "解锁❤️村民感恩",
    "Unlocked 🎲Underground Connection": "解锁 🎲地下联系",
    "Unlocked 🔁Understanding of the Reset": "解锁 🔁重置理解",
    "Unlocked 🗻High Altitude Climbing": "解锁 🗻高海拔攀爬",
    "Unlocked 🦶Experienced Traveler": "解锁 🦶经验丰富的旅行者",
    "🔎Search, 🗺️Travel, 🛡️Fortitude": "🔎搜索，🗺️旅行，🛡️坚韧",
    "🔨Crafting, 🔎Search": "🔨制作，🔎搜索",
    "🔮Magic, 🔎Search": "🔮魔术，🔎搜索",
    "🗺️Travel, ⚔️Combat": "🗺️旅行，⚔️战斗",
    "🧥Worm Hide Coat Item": "🧥蠕虫隐藏外套项目",
    "🚫Giant Sandworm": "🚫巨型沙虫",
    "🚫Horde of Lizardfolk": "🚫蜥蜴部落",
    "🚫Kraken": "🚫海妖",
    "🚫Sleepy Djinn": "🚫沉睡的精灵",
    "Talk to the Djinn": "与精灵交谈",
    "Unlocked ⚓Sunken Treasure": "已解锁⚓沉没的宝藏",
    "Unlocked 🏯Found Lost Temple": "已解锁🏯找到失落的庙宇",
    "Unlocked 👣Walk Without Rhythm": "已解锁👣没有节奏地行走",
    "⚡Bottled Lightning Item": "瓶装闪电 物品",
    "🔎Search, 🧠Study": "🔎搜索，🧠研究",
    "🕊️Griffin Quill Item": "🕊️狮鹫羽毛 物品",
    "🪂Mystery Perk": "🪂神秘增益",
    "🚫Griffin": "🚫狮鹫",
    "Bottled Lightning": "瓶装闪电",
    "Chat with the Crew": "与船员交谈",
    "Conduct Emergency Repairs": "进行紧急维修",
    "Fly to the Volcano": "飞往火山",
    "Go Skydiving": "高空跳伞",
    "Griffin": "狮鹫",
    "Harness Lightning": "驾驭闪电",
    "Plot the Course": "规划航线",
    "The next Boss Task you start is 2x as fast": "你开启的下一个首领任务速度翻倍",
    "This stacks with Scroll of Haste": "可与急速卷轴效果叠加",
    "This was your 62nd Energy Reset": "这是你的第62次能量重置",
    "Watch the Clouds Go By": "静观流云",
    "⚔️Combat, 🗡️Subterfuge": "⚔️战斗，🗡️诡计",
    "🌠Magical Essence Items": "🌠魔法精华物品",
    "🔮Magic, 🔨Crafting": "🔮魔法，🔨制作",
    "🕸️Dreamcatcher Item": "🕸️捕梦网物品",
    "Build a Hang Glider": "建造悬挂式滑翔机",
    "Build Airship": "建造飞艇",
    "Design Next Ritual": "设计下一个仪式",
    "Placate the Voices in Your Head": "安抚脑海中的声音",
    "Venture Forth": "奋勇前行",
    "⚡Bottled Lightning": "⚡瓶装闪电",
    "💍Magic Ring Item": "💍魔法戒指 物品",
    "💍Mystery Perk": "💍神秘增益",
    "🔥Heat Essence Items": "🔥火焰精粹 物品",
    "🦇Wings of Shadow Item": "🦇暗影之翼 物品",
    "🚫Cast the Ring into the Fire": "🚫将戒指投入火焰",
    "🚫Winged Demon": "🚫翼魔",
    "Bottle Lava for the Ritual": "为仪式灌装熔岩",
    "Cast the Ring into the Fire": "将戒指投入火焰",
    "Disabled due to this requiring a 💍Magic Ring Item": "因需要💍魔法戒指物品，功能已禁用",
    "Enter Crevice": "进入裂隙",
    "Get Used to the Heat": "适应高温",
    "Harness Heat": "驾驭火焰",
    "Sneak Past Beings of Pure Heat": "潜行穿过纯火元素生物",
    "Try to Use Lava for Forging": "尝试用熔岩锻造",
    "Winged Demon": "翼魔",
    "Perk(s)": "特权",
    "* Perk is only gained on completing all Reps of the Task": "* 只有完成该任务的所有步骤后才能获得特权",
    "** Skill gain as range since you're expected to run out of 🔋Energy before fully completing this Task": "** 由于您预计会在完全完成此任务之前耗尽 🔋能量，所以技能提升的幅度会相应增加",
    "♟️XP (Magic Ring)": "♟️经验值（魔法戒指）",
    "Next 1 Task reps give 5x as much XP": "接下来的 1 个任务步骤将额外提供 5 倍的经验值",
    "Skill Gains**": "技能增益**",
    "🙏Ascension has its starting level increased by only half": "🙏转生起始等级仅提升一半",
    "1-tick Tasks (except Travel) are now automatically completed when you enter a Zone": "进入区域时，1帧任务（旅行除外）将自动完成",
    "1-tick Tasks are now free": "1帧任务现在无需消耗资源",
    "100, multiplied by 2.12 for each Zone past 15": "每超过15区域，数值×2.12倍，基础值100",
    "Additional ✨Divine Spark for reaching Zone 23: 28.7k": "抵达23区域额外获得✨神性火花：28.7k",
    "Boss Tasks no longer get removed from Automation on Prestige": "声望重置后，首领任务不会从自动任务列表中移除",
    "Deenergized": "能量耗尽状态",
    "Divine Lightning": "神圣闪电",
    "Divine Speed": "神圣迅捷",
    "Energized": "能量充盈状态",
    "Increases ♟️XP and 🌀Attunement gain by 50%": "♟️经验值与🌀共鸣获取量提升50%",
    "Increases Max 🔋Energy by 20": "🔋最大能量值提升20",
    "Increases starting skill levels by 100": "初始技能等级提升100",
    "Increases the 🔋Energy gain from 💭Energetic Memory by 5%": "💭能量记忆提供的🔋能量获取量提升5%",
    "Increases the exponent for the ✨Divine Spark gain calculation by 0.12": "✨神性火花获取计算的指数提升0.12",
    "Makes the game tick 1% faster (additively) for every 4 Max 🔋Energy beyond 100": "最大🔋能量每超出100点，游戏运行速度额外提升1%（叠加计算）",
    "Mastery of Time": "时间精通",
    "No effect on 🔋Energy use, but makes tasks take less real-world time": "不影响🔋能量消耗，但可缩短任务的现实耗时",
    "Permanently unlocks the ⌚Minor Time Compression and ⏰Major Time Compression Perks": "永久解锁⌚轻度时间压缩与⏰重度时间压缩增益",
    "Permanently unlocks the 💭Energetic Memory Perk": "永久解锁💭能量记忆增益",
    "Reduces 🔋Energy drain by 10%": "🔋能量消耗降低10%",
    "See Beyond the Veil": "视界穿透",
    "Squares the Max 🔋Energy gain after Zone 10": "区域10之后，最大🔋能量获取量按平方计算",
    "The auto-completion is not applied to Zones you've not set to be automated (in case you want to do things like use a Magic Ring)": "自动完成功能不会应用于未设置自动执行的区域（便于你使用魔法戒指等操作）",
    "Transcendant Aptitude": "超凡天赋",
    "Transcendant Memory": "超凡记忆",
    "Unlocks five new tasks before Zone 20": "在区域20前解锁五个全新任务",
    " Item": "物品",
    "🤪Mad Contraption Items": "奇妙奇物藏品",
    "Amazing Speed": "极速如风",
    "Army Food": "军团食粮",
    "Ascend to Godhood": "转生成神",
    "Ascended": "神格圆满",
    "Avoided Godly Revenge": "免遭神罚",
    "Build Void-inspired Contraption": "构筑虚空造物",
    "Close Prestige Menu": "关闭转生菜单",
    "Communed with Damned Souls": "与亡魂通灵",
    "Compulsive Notetaking": "偏执记录",
    "Crafting Breakthrough": "锻造突破",
    "Defied the Gods": "违抗神明",
    "Demonstrate New Powers": "展露新权能",
    "Destroyed the Ring": "击碎魔戒",
    "Divine Attunement": "神性亲和",
    "Divine Note": "神之笔记",
    "Divine Power": "神之力量",
    "Divine Spark": "神性星火",
    "Divine Supremacy": "至高神权",
    "Diviner Knowledge": "先知学识",
    "Doubles ✨Divine Spark gain": "神性星火获取翻倍",
    "Doubles ✨Divine Spark Gain": "神性星火获取翻倍",
    "Doubles 🌀Attunement Gain": "神性亲和进度翻倍",
    "Embrace Divinity": "拥抱神性",
    "Every Perk unlocked increases Task Speed by 1% (multiplicative)": "每解锁一项天赋，任务速度乘法提升1%",
    "Gazed Beyond the Veil": "看破虚妄",
    "Glasses": "神视眼镜",
    "Go Spread Your Word": "传播神谕",
    "Godly Travel": "神域穿梭",
    "Griffin Quill": "狮鹫羽笔",
    "Heat Essence": "炽热能核",
    "Herald of the Gods": "神之使者",
    "Improves ♟️XP gain by 100%": "经验值获取提升100%",
    "Improves ✨Divine Spark gain by 25%": "神性星火获取提升25%",
    "Improves 🎭Charisma and 🛡️Fortitude Task speed by 30%": "魅力、坚韧任务速度提升30%",
    "Improves 🎭Charisma, ⚔️Combat, and 🙏Ascension Task speed by 30%": "魅力、战斗、转生任务速度提升30%",
    "Improves 🎭Charisma, 🗡️Subterfuge, and 🔎Search Task speed by 30%": "魅力、诡计、探索任务速度提升30%",
    "Improves 🔎Search Task speed by 100% each": "每项🔎探索任务速度提升100%",
    "Improves 🔎Search, 🗺️Travel, and 🛡️Fortitude Task speed by 50% each": "🔎探索、🗺️旅行、🛡️坚韧任务速度每项提升50%",
    "Improves 🔮Magic, 🧠Study, and 🗡️Subterfuge Task speed by 300% each": "🔮魔法、🧠学识、🗡️诡计任务速度每项提升300%",
    "Improves 🔮Magic, 🙏Ascension, and ⚔️Combat Task speed by 500% each": "🔮魔法、🙏转生、⚔️战斗任务速度每项提升500%",
    "Improves 🗡️Subterfuge, 🛡️Fortitude, 🎭Charisma, and 🙏Ascension Task speed by 30%": "诡计、坚韧、魅力、转生任务速度提升30%",
    "Improves 🧠Study and ⚔️Combat Task speed by 30%": "🧠学识、⚔️战斗任务速度提升30%",
    "Improves 🧠Study and 🔎Search Task speed by 30% each": "🧠学识、🔎探索任务速度每项提升30%",
    "Improves 🧠Study, 🔨Crafting, and ⚔️Combat Task speed by 100% each": "🧠学识、🔨制作、⚔️战斗任务速度每项提升100%",
    "Improves 🙏Ascension and 🛡️Fortitude Task speed by 30%": "转生、坚韧任务速度提升30%",
    "Improves 🙏Ascension, ⚔️Combat, 🔮Magic, and 🧠Study Task speed by 25%": "🙏转生、⚔️战斗、🔮魔法、学识任务速度提升25%",
    "Improves 🙏Ascension, 🧠Study, and 🔮Magic Task speed by 100%": "🙏转生、🧠学识、🔮魔法任务速度提升100%",
    "Improves the speed of Charisma and Ascension Tasks by 25%": "魅力、转生任务速度提升25%",
    "Improves the speed of Travel, Mandatory, and Prestige Tasks by 20%": "远行、强制、转生任务速度提升20%",
    "Increases ♟️XP gain by 100%": "♟️经验值获取增加100%",
    "Increases 🔋Energy Gain from Items by 20%": "从道具获取的🔋能量增加20%",
    "Increases Max 🔋Energy by 1000": "最大🔋能量值增加1000",
    "Lick Your Wounds": "疗伤自愈",
    "Light": "圣光",
    "Limitless Power": "无尽神力",
    "Mad Contraption": "疯狂造物",
    "Makes 🌀Attunement apply to 🔨Crafting": "使亲和效果作用于锻造",
    "Makes 🗺️Travel Tasks 5x faster": "远行任务速度提升5倍",
    "Makes all Tasks 5x faster": "所有任务速度提升5倍",
    "Makes Mandatory Tasks 5x faster": "强制任务速度提升5倍",
    "Mandatory Schmandatory": "强制皆是空谈",
    "Multiplier from 🚫Defied the Gods: 1.25": "逆神效果倍率：1.25倍",
    "Multiplies ♟️XP Gain by 5": "经验值获取倍率×5",
    "Multiplies 🌀Attunement Gain by 1.25": "亲和进度获取倍率×1.25",
    "Multiplies 💪Power and 🌀Attunement Gain by 5": "力量、亲和进度获取倍率×5",
    "One more level would increase ✨Divine Spark gain at Zone 19 by 16%, and 62% at Zone 30": "再升一级，第19区域神性星火获取提升16%，第30区域提升62%",
    "Overcame Fear of Skydiving": "克服高空坠惧",
    "Perky": "天赋加成",
    "Plot Your Revenge": "筹划复仇",
    "Ponder Your Exile": "沉思放逐",
    "Prepared Final Ritual": "筹备终末仪式",
    "Purged Demonic Influences": "涤除魔祟侵蚀",
    "Recording": "记录存档",
    "Returned Herald's Head": "归回神使之首",
    "Ritual Sacrifice": "仪式献祭",
    "Ritual Symbol": "仪式徽记",
    "Second in Command": "二把手",
    "Send Herald's Head to the Gods": "献祭神使之首于诸神",
    "Spite the Gods": "忤逆诸神",
    "Start every reset with at minimum 2 of each of 🐇Scrolls of Haste, 📚Books, 🛠️Crafting Recipes, 📜Divine Notes, and 🕊️Griffin Quills": "每次重置开局，急速卷轴、典籍、锻造配方、神之笔记、狮鹫羽笔各类道具最低各持有2个",
    "Studied Underground Forge": "研习地底熔炉",
    "Supply Lines": "物资补给",
    "Survived the Void": "虚空余生",
    "Takes effect if you would keep fewer of the given Item on Energy Reset": "能量重置时，若留存道具数量偏少则生效",
    "Understanding Leviathan": "洞悉深海巨兽",
    "Unparalleled Learning": "无双学识",
    "Void Essence": "虚空精元",
    "Whine About the Void": "慨叹虚空",
    "Wings of Shadow": "暗影之翼",
    "🔮Magic, 🙏Ascension": "🔮魔法，🙏转生",
    "🔮Magic, 🙏Ascension, and ⚔️Combat Task speed increased 1500%": "🔮魔法，🙏转生，和⚔️战斗任务速度提升1500%",
    "🗡️Subterfuge, 🛡️Fortitude": "🗡️诡计，🛡️坚韧",
    "🧠Study, ⚔️Combat": "🧠学识，⚔️战斗",
    "🩸Ritual Sacrifice Items": "🩸仪式献祭道具",
    "Appoint Second in Command": "任命副手",
    "Assemble Your Forces": "集结麾下兵力",
    "Attract Followers": "吸引追随者",
    "Avatar of the Gods": "神之化身",
    "Avoid the Gods' Revenge": "规避神之复仇",
    "Break Down the Gates": "冲破天门",
    "Bring Your Army to Heaven": "率军登天",
    "Build Staircase to Heaven": "筑造登天阶梯",
    "Conduct Ritual Sacrifice": "举行仪式献祭",
    "Cook for the Army": "为军团备粮",
    "Demigod": "半神",
    "Gather Intel": "搜集情报",
    "Gather More Troops": "扩充兵力",
    "Gather Some Divine Spark": "汲取神性星火",
    "Inspire Your Troops": "鼓舞麾下将士",
    "Make Battle Plan": "制定作战计划",
    "Plan Eternity in Heaven": "谋划天界永生",
    "Ponder Next Moves": "思索后续布局",
    "Prepare Final Ritual": "筹备终末仪式",
    "Protect Your Supply Lines": "守护补给线路",
    "Rally Your Troops": "集结麾下军队",
    "Record Rousing Speech": "记录激昂演说",
    "Take Your Place in Heaven": "登临天界神位",
    "Taunt the Gods": "嘲讽诸神",
    "Train Your Fighters": "训练战士",
    "Train Your Magicians": "训练法师",
    "⛏️Mystery Perk": "⛏️神秘特质",
    "👓Glasses Item": "👓眼镜道具",
    "🚫Floating Ball of Eyes": "🚫浮空眼之球",
    "Cast underwater Breathing Spell": "施放水下呼吸法术",
    "Confirm": "确认",
    "Do Prestige": "进行转生",
    "Exit Through a Moonpool": "经由月池离开",
    "Find Rare Mushroom Reagent": "寻找稀有蘑菇素材",
    "Floating Ball of Eyes": "浮空眼之球",
    "Join Underground Fight Club": "加入地下地下格斗俱乐部",
    "Practice the Local Dialect": "学习当地方言",
    "Steal Farmed Cave Insects": "盗取人工培育的洞穴昆虫",
    "Study Underground Forge": "研究地下熔炉",
    "Will also remove all Boss Tasks from automation": "同时会移除自动化列表内所有首领任务",
    "📖How to Write Perk": "📖如何书写特权",
    "📖How to Read Perk": "📖如何阅读特权",
    "⛺Camping Equipment Items": "⛺露营装备物品",
    "Unlocked ⏰Major Time Compression": "解锁 ⏰ 重大时间压缩",
    "⚫Mystery Perk": "⚫神秘特质",
    "⚫Void Essence Item": "⚫虚空精华道具",
    "💡Light Items": "💡光明道具",
    "🚫Foreboding Presence": "🚫不祥气息",
    "Avoid Alerting the Gods": "避免惊动神明",
    "Avoid Going Insane": "避免精神失控",
    "Create Light": "创造光亮",
    "Exit the Void": "脱离虚空",
    "Figure Out How to Leave": "探寻离开的方法",
    "Foreboding Presence": "不祥气息",
    "Search the Void": "探索虚空",
    "Talk to Yourself": "自言自语",
    "☯️Ritual Symbol Items": "☯️仪式符文道具",
    "🦑Calamari Item": "🦑鱿鱼素材道具",
    "🚫Half-Kraken": "🚫半体巨妖",
    "🛡️Fortitude, 🗺️Travel": "🛡️坚韧、🗺️远行",
    "🛡️Fortitude, 🙏Ascension": "🛡️坚韧、🙏升华",
    "Attempt to Enter Hell": "尝试踏入地狱",
    "Catch Passing Fish": "捕捉途经游鱼",
    "Collect Quills": "收集翎羽",
    "Dare the Gods to Intervene": "挑衅神明强行干涉",
    "Deep-water Swimming": "深水潜游",
    "Defy the Gods": "违抗神明意志",
    "Determine Deepest Point": "探寻海域最深之处",
    "Dig a Tunnel": "挖掘地底隧道",
    "Etch Ritual Symbols": "铭刻仪式符文",
    "Gaze Beyond the Veil": "凝视帷幕之外",
    "Go to Crab Rave": "前往蟹群狂欢之地",
    "Half-Kraken": "半体巨妖",
    "Inspect Leviathan": "检视利维坦巨兽",
    "Journey Into the Depths": "深入幽暗深海",
    "Prepare for the Pressure": "做好高压环境防护",
    "Prepare to Face the Gods": "准备直面诸神",
    "Purge Demonic Influence": "净化恶魔侵蚀之力",
    "Steal Glasses": "窃取眼镜",
    "Study Divinity": "研习神性奥秘",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Zone 1 - The Village": "区域 1 - 村庄",
    "Zone 2 - The Village Watch": "区域 2 - 村庄守卫",
    "Zone 3 - The Raid": "区域 3 - 突袭",
    "Zone 4 - The Wilderness": "区域 4 - 荒野",
    "Zone 5 - The Cave System": "区域 5 - 洞穴系统",
    "Zone 6 - The Road to the City": "区域 6 - 通往城市的路",
    "Zone 7 - The City Outskirts": "区域 7 - 城市郊区",
    "Zone 8 - The City": "区域 8 - 城市",
    "Zone 9 - The Forest": "区域 9 - 森林",
    "Zone 10 - The Magician": "区域 10 - 魔术师",
    "Zone 11 - The Ocean": "区域 11 - 海洋",
    "Zone 12 - The Island": "区域 12 - 岛屿",
    "Zone 13 - The Desert": "区域 13 - 沙漠",
    "Zone 14 - The Oasis": "区域 14 - 绿洲",
    "Zone 15 - The Ritual": "区域 15 - 仪式",
    "Zone 16 - The Dream": "区域 16 - 梦境",
    "Zone 17 - The Metropolis": "区域 17 - 大都市",
    "Zone 18 - The Foothills": "区域 18 - 山麓",
    "Zone 19 - The Dragon's Lair": "区域 19 - 龙穴",
    "Zone 20 - The Place of Power": "区域 20 - 权力之所",
    "Zone 21 - The Sky": "区域 21 - 天空",
    "Zone 22 - The Volcano": "区域 22 - 火山",
    "Zone 23 - The Underworld": "区域 23 - 冥界",
    "Zone 24 - The Depths of the Sea": "区域 24 - 海洋深处",
    "Zone 25 - The Deepest Deep": "区域 25 - 最深的深渊",
    "Zone 26 - The Void": "区域 26 - 虚空",
    "Zone 27 - The Return": "区域 27 - 归来",
    "Zone 28 - The Cult": "区域 28 - 崇拜",
    "Zone 29 - The War Preparations": "区域 29 - 战争准备",
    "Zone 30 - The Gates of Heaven": "区域 30 - 天堂之门",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "🍄📚🌲🌿💎💧🦴🌠🧞⚫🩸": "🍄📚🌲🌿💎💧🦴🌠🧞⚫🩸",
    "🏹📦🪓🔪👢🐲🤪🩸": "🏹📦🪓🔪👢🐲🤪🩸",
    "💰🔗🐺🔥📼": "💰🔗🐺🔥📼",
    "🕯️🦴🧞🏺🦇☯️✨🩸": "🕯️🦴🧞🏺🦇☯️✨🩸",
    "☀️": "☀️",
    "☯️": "☯️",
    "⚫": "⚫",
    "⛏️": "⛏️",
    "✨": "✨",
    "🌋": "🌋",
    "🌿🛠️🤪": "🌿🛠️🤪",
    "🍄📚🌲🌿💎💧🦴🌠🧞⚫": "🍄📚🌲🌿💎💧🦴🌠🧞⚫",
    "🍄🦴📜👓💡": "🍄🦴📜👓💡",
    "🍱": "🍱",
    "🎒🦴🦇📜💡": "🎒🦴🦇📜💡",
    "🏹📦🪓🔪👢🐲🤪": "🏹📦🪓🔪👢🐲🤪",
    "🐋": "🐋",
    "👀": "👀",
    "👓": "👓",
    "👹": "👹",
    "👻": "👻",
    "👼": "👼",
    "💡": "💡",
    "💰🔗🐺🔥": "💰🔗🐺🔥",
    "📚🕊️📜⚫🤪": "📚🕊️📜⚫🤪",
    "📦🎒⛺🌲🌵🐺💧🧥👢🐲💡": "📦🎒⛺🌲🌵🐺💧🧥👢🐲💡",
    "📦💎🔪🔗⚫": "📦💎🔪🔗⚫",
    "📼": "📼",
    "🕯️🦴🧞🏺🦇☯️✨": "🕯️🦴🧞🏺🦇☯️✨",
    "🤕": "🤕",
    "🤪": "🤪",
    "🩸": "🩸",
    "🙇‍♂️": "🙇‍♂️",
    "🚫": "🚫",
    "🛣️": "🛣️",
    "⚓🤿": "⚓🤿",
    "💀⚓": "💀⚓",
    "📿🏯🤿🔷🧙‍♂️": "📿🏯🤿🔷🧙‍♂️",
    "⚙": "⚙",
    "♻": "♻",
    "🍲": "🍲",
    "📖": "📖",
    "ℹ": "ℹ",
    "📝": "📝",
    "🏹": "🏹",
    "❤️": "❤️",
    "💰": "💰",
    "🪓": "🪓",
    "🎲👣": "🎲👣",
    "🦶👣": "🦶👣",
    "⌚": "⌚",
    "⚓": "⚓",
    "🌵": "🌵",
    "🌿": "🌿",
    "🍄": "🍄",
    "🎒": "🎒",
    "🎖️": "🎖️",
    "👣": "👣",
    "🎲": "🎲",
    "📚": "📚",
    "📦": "📦",
    "📿": "📿",
    "🏯": "🏯",
    "🐇": "🐇",
    "🗻": "🗻",
    "🔥": "🔥",
    "🦶": "🦶",
    "🐟": "🐟",
    "⚡️": "⚡️",
    "🌀": "🌀",
    "❤️🎲🎖️": "❤️🎲🎖️",
    "🌲": "🌲",
    "💎": "💎",
    "🔗": "🔗",
    "🐺": "🐺",
    "🔪": "🔪",
    "🦑": "🦑",
    "🦴": "🦴",
    "🧥": "🧥",
    "🍄🌿": "🍄🌿",
    "🎒🔥🌵": "🎒🔥🌵",
    "🏹📦": "🏹📦",
    "⚖️": "⚖️",
    "💧": "💧",
    "💭": "💭",
    "🕯️": "🕯️",
    "💀": "💀",
    "🧞": "🧞",
    "💃": "💃",
    "🕰️": "🕰️",
    "🤿": "🤿",
    "📿🔷🧙‍♂️": "📿🔷🧙‍♂️",
    "🦶👣🔷": "🦶👣🔷",
    "📖🧙‍♂️": "📖🧙‍♂️",
    "❤️🎲🎖️⚖️💃🧱🐉": "❤️🎲🎖️⚖️💃🧱🐉",
    "🎖️💀🏔️🐉": "🎖️💀🏔️🐉",
    "🎲👣👥": "🎲👣👥",
    "🏯🤿": "🏯🤿",
    "⚓💀": "⚓💀",
    "⏰": "⏰",
    "🌠": "🌠",
    "🏔️": "🏔️",
    "🏺": "🏺",
    "🐉": "🐉",
    "🐲": "🐲",
    "👢": "👢",
    "👥": "👥",
    "💍": "💍",
    "💤": "💤",
    "📜": "📜",
    "🔷": "🔷",
    "🕸️": "🕸️",
    "🛠️": "🛠️",
    "🦟": "🦟",
    "🧱": "🧱",
    "🧙‍♂️": "🧙‍♂️",
    "⛺": "⛺",
    "🔁": "🔁",
    "🍄📚": "🍄📚",
    "📦🎒": "📦🎒",
    "⚡": "⚡",
    "📦🎒⛺": "📦🎒⛺",
    "🍄📚🌿": "🍄📚🌿",
    "🌿🛠️": "🌿🛠️",
    "🍄📚🌲💎🌿💧🦴🧞🌠": "🍄📚🌲💎🌿💧🦴🧞🌠",
    "🍄🦴": "🍄🦴",
    "🎒🦴": "🎒🦴",
    "🏹📦🪓🔪👢🐲": "🏹📦🪓🔪👢🐲",
    "💰🔗🐺": "💰🔗🐺",
    "📦🎒⛺🌲🐺🌵💧🧥👢🐲": "📦🎒⛺🌲🐺🌵💧🧥👢🐲",
    "📦🔪💎🔗": "📦🔪💎🔗",
    "🕊️": "🕊️",
    "🦴🕯️🧞🏺": "🦴🕯️🧞🏺",
    "🪂": "🪂",
    "🦇": "🦇",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "♟️XP: ": "♟️经验值: ",
    "💪Power: ": "💪力量: ",
    "Skills: ": "技能: ",
    "Prestige: ": "声望: ",
    "Speed multiplier: x": "速度乘数: x",
    "🌀Attunement: ": "🌀点化: ",
    "🗡️Subterfuge - Level ": "🗡️诡计 - 等级 ",
    "🧠Study - Level ": "🧠学习 - 等级 ",
    "🔎Search - Level ": "🔎搜搜 - 等级 ",
    "🎭Charisma - Level ": "🎭魅力 - 等级 ",
    "🔨Crafting - Level ": "🔨制作 - 等级 ",
    "⚔️Combat - Level ": "⚔️战斗 - 等级 ",
    "🗺️Travel - Level ": "🗺️旅行 - 等级 ",
    "⛺Survival - Level ": "⛺生存 - 等级 ",
    "🔋Energy - ": "🔋能量 - ",
    "🔨Crafting is now ": "🔨制作 现在是 ",
    "⚔️Combat is now ": "⚔️战斗 现在是 ",
    "🧠Study is now ": "🧠学习 现在是 ",
    "🗺️Travel is now ": "🗺️旅行 现在是 ",
    "🔎Search is now ": "🔎搜索 现在是 ",
    "⛺Survival is now ": "⛺生存 现在是 ",
    "🗡️Subterfuge is now ": "🗡️诡计 现在是 ",
    "🎭Charisma is now ": "🎭魅力 现在是 ",
    "⚔️Combat: ": "⚔️战斗: ",
    "🎭Charisma: ": "🎭魅力: ",
    "🧠Study: ": "🧠学习: ",
    "🔎Search: ": "🔎搜索: ",
    "🗡️Subterfuge: ": "🗡️诡计: ",
    "🔨Crafting: ": "🔨制作: ",
    "⛺Survival: ": "⛺生存: ",
    "🗺️Travel: ": "🗺️旅行: ",
    "Unlocked Skill ": "已解锁技能 ",
    "New highest Zone: ": "新的最高区域：",
    "From level: x": "来自等级: x",
    "From other sources: x": "来自其他来源: x",
    "New highest Zone fully completed: ": "新的完全完成最高区域:",
    "🛡️Fortitude - Level ": "🛡️坚韧 - 等级 ",
    "🔮Magic - Level ": "🔮魔法 - 等级 ",
    "Improves ⛺Survival and 🛡️Fortitude Task speed by ": "提升 ⛺生存 和 🛡️坚韧 任务速度 ",
    "Improves 🐻Druid Task speed by ": "提升 🐻德鲁伊 任务速度 ",
    "Improves 🗡️Subterfuge Task speed by ": "提升 🗡️诡计 任务速度 ",
    "Improves ⚔️Combat Task speed by ": "提升 ⚔️战斗 任务速度 ",
    "Improves ⚔️Combat and 🎭Charisma Task speed by ": "提升 ⚔️战斗 和 🎭魅力 任务速度 ",
    "Improves ⚔️Combat and 🛡️Fortitude Task speed by ": "提升 ⚔️战斗 和 🛡️坚韧 任务速度 ",
    "Improves 🎭Charisma Task speed by ": "提升 🎭魅力 任务速度 ",
    "Improves 🎭Charisma and 🙏Ascension Task speed by ": "提升 🎭魅力 和 🙏转生 任务速度 ",
    "Improves 🧠Study Task speed by ": "提升 🧠学习 任务速度 ",
    "Improves 🗺️Travel Task speed by ": "提升 🗺️旅行 任务速度 ",
    "Improves 🗺️Travel and ⛺Survival Task speed by ": "提升 🗺️旅行 和 ⛺生存 任务速度 ",
    "Improves 🔮Magic Task speed by ": "提升 🔮魔法 任务速度 ",
    "Improves 🔮Magic and 🗺️Travel Task speed by ": "提升 🔮魔法 和 🗺️旅行 任务速度 ",
    "Improves 🔮Magic and 🧠Study Task speed by ": "提升 🔮魔法 和 🧠学习 任务速度 ",
    "Improves 🔨Crafting Task speed by ": "提升 🔨制作 任务速度 ",
    "Improves 🙏Ascension Task speed by ": "提升 🙏转生 任务速度 ",
    "Improves 🔨Crafting and 🐻Druid Task speed by ": "提升 🔨制作 和 🐻德鲁伊 任务速度 ",
    "Improves 🔮Magic and 🔎Search Task speed by ": "提升 🔮魔法 和 🔎搜索 任务速度 ",
    "Increases ⚔️Combat and 🛡️Fortitude speed by ": "提高 ⚔️战斗 和 🛡️坚韧 速度 ",
    "Increases 🐻Druid, 🔮Magic, and 🧠Study speed by ": "提高 🐻德鲁伊, 🔮魔法, 盒 🧠学习 速度 ",
    "🐻Druid - Level ": "🐻德鲁伊 - 等级 ",
    "💪Power - ": "💪力量 - ",
    "🌀Attunement - ": "🌀点化 - ",
    "🔨Crafting and 🐻Druid Task speed increased ": "🔨制作 和 🐻德鲁伊 任务速度提高 ",
    "🔮Magic and 🔎Search Task speed increased ": "🔮魔法 和 🔎搜索 任务速度提高 ",
    "🗺️Travel and ⛺Survival Task speed increased ": "🗺️旅行 和 ⛺生存 任务速度提高 ",
    "🛡️Fortitude Task speed increased ": "🛡️坚韧 任务速度提高 ",
    "🎭Charisma Task speed increased ": "🎭魅力 任务速度提高 ",
    "⛺Survival Task speed increased ": "⛺生存 任务速度提高 ",
    "🎭Charisma and 🗡️Subterfuge Task speed increased ": "🎭魅力 和 🗡️诡计 任务速度提高 ",
    "⛺Survival, 🔮Magic, and 🐻Druid Task speed increased ": "⛺生存, 🔮魔法, 和 🐻德鲁伊 任务速度提高 ",
    "🎭Charisma and ⛺Survival Task speed increased ": "🎭魅力 和 ⛺生存 任务速度提高 ",
    "🗡️Subterfuge and ⛺Survival Task speed increased ": "🗡️诡计 和 ⛺生存 任务速度提高 ",
    "⛺Survival and 🛡️Fortitude Task speed increased ": "⛺生存 和 🛡️坚韧 任务速度提高 ",
    "🙏Ascension and 🔮Magic Task speed increased ": "🙏转生 和 🔮魔法 任务速度提高 ",
    "🔎Search and 🐻Druid Task speed increased ": "🔎搜索 和 🐻德鲁伊 任务速度提高 ",
    "🙏Ascension Task speed increased ": "🙏转生 任务速度提高 ",
    "🧠Study Task speed increased ": "🧠学习 任务速度提高 ",
    "🔮Magic Task speed increased ": "🔮魔法 任务速度提高 ",
    "🗡️Subterfuge Task speed increased ": "🗡️诡计 任务速度提高 ",
    "🔨Crafting Task speed increased ": "🔨制作 任务速度提高 ",
    "⚔️Combat Task speed increased ": "⚔️战斗 任务速度提高 ",
    "⚔️Combat and 🛡️Fortitude Task speed increased ": "⚔️战斗 和 🛡️坚韧 任务速度提高 ",
    "🔮Magic is now ": "🔮魔法 现在 ",
    "🐻Druid is now ": "🐻德鲁伊 现在 ",
    "🙏Ascension is now ": "🙏转生 现在 ",
    "🛡️Fortitude is now ": "🛡️坚韧 现在 ",
    "🛡️Fortitude: ": "🛡️坚韧: ",
    "🐻Druid: ": "🐻德鲁伊: ",
    "🔮Magic: ": "🔮魔法: ",
    "✨Divine Spark": "✨神圣的火花",
    "🙏Ascension - Level ": "🙏转生 - 等级 ",
    "🙏Ascension: ": "🙏转生: ",
    "Increases 🐻Druid, 🔮Magic, 🧠Study, and 🔎Search speed by ": "提高🐻德鲁伊，🔮魔法，🧠学习和🔎搜索速度 ",
    "Highest Zone fully completed: ": "完全完成的最高区域：",
    "Highest Zone reached: ": "达到的最高区域: ",
    "Changes since you last played ": "变化自从你上次玩游戏 ",
    "Hotkey: ": "快捷键: ",
    "Highest Zone reached (any Prestige): ": "到达的最高区域（任意声望）：",
    "Highest Zone fully completed (any Prestige): ": "全部完成的最高区域（任意声望）：",
    "Current Effect: ": "当前效果: ",
    "Prestiges done: ": "完成声望: ",
    "Multiplies Task speed by ": "乘以任务速度 ",
    " gain if you Prestige now: ": " 增益如果你现在声望: ",
    "Additional ✨Divine Spark for reaching Zone 9: ": "达到第 9 区域时额外获得✨神圣火花：",
    "🗺️Travel and 🛡️Fortitude Task speed increased ": "🗺️旅行 和 🛡️坚韧 任务速度提高 ",
    "🧠Study and 🔮Magic Task speed increased ": "🧠学习 和 🔮魔法 任务速度提高 ",
    "Current effect: ": "当前效果：",
    "Effect in current Zone: ": "当前区域效果：",
    "Highest Zone fully completed currently: ": "当前已完成的最高区域等级：",
    "⏰Ticks per second: ": "⏰ 每秒Tick: ",
    "Increases 🔮Magic, 🧠Study, and 🔎Search speed by ": "提升🔮魔法、🧠研究和🔎搜索速度 ",
    "Multiplier from 💤Awakening: ": "来自💤觉醒的乘数：",
    "Additional ✨Divine Spark for reaching Zone ": "额外的✨神圣火花，用于进入区域 ",
    "Increases 🔮Magic, 🧠Study, 🔎Search, and 🔨Crafting speed by ": "🔮魔法、🧠学识、🔎探索、🔨制作任务速度增加 ",
    "🔎Search Task speed increased ": "🔎搜索任务速度提高了 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " speed)": " 速度)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+) \(x([\d\.]+)$/,
    /^\+([\d\.]+)\%$/,
    /^\+([\d\.]+)k\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \(([\d\.]+)-([\d\.]+)-([\d\.]+)\)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^x([\d\.]+)k$/,
    /^\+([\d\.]+)k$/,
    /^([\d\.]+): ([\d\.]+)k$/,
    /^([\d\.]+): ([\d\.]+)M$/,
    /^x([\d\.]+)M$/,
    /^x([\d\.]+)B$/,
    /^x([\d\.]+)T$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)M\/([\d\.]+)M$/,
    /^([\d\.]+)B\/([\d\.]+)B$/,
    /^([\d\.]+)M\/([\d\.]+)B$/,
    /^([\d\.]+)M\/([\d\.]+)T$/,
    /^([\d\.]+)B\/([\d\.]+)T$/,
    /^([\d\.]+)T\/([\d\.]+)T$/,
    /^([\d\.]+)k\/([\d\.]+)M$/,
    /^([\d\.]+)k\/([\d\.]+)k$/,
    /^([\d\.]+)Qa\/([\d\.]+)Qa$/,
    /^([\d\.]+)Qi\/([\d\.]+)Qi$/,
    /^([\d\.]+)(.+)\/([\d\.]+)(.+)$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+)No$/,
    /^([\d\.]+)Sp$/,
    /^([\d\.]+)Sx$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\<([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\(\+([\d\.,]+)\)$/,
    /^([\d\.,]+) \(\+([\d\.,]+)\)$/,
    /^\+([\d\.]+)k \(x([\d\.]+)$/,
    /^([\d\.]+) \(\+([\d\.]+)k\)$/,
    /^([\d\.]+)k \(x([\d\.]+)k\)$/,
    /^([\d\.]+)(.+) \(\+([\d\.]+)(.+)\)$/,
    /^: ([\d\.]+)(.+) \(\+([\d\.]+)(.+)\)$/,
    /^\+([\d\.]+)(.+) \(x([\d\.]+)$/,
    /^ \- ([\d\.]+)(.+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+) \- ([\d\.]+)$/,
    /^ \- ([\d\.]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Will give (.+) ✨Divine Spark, but reset everything except that which is granted by Divinity purchases$/, '可获得 $1 ✨神性火花，除神性购买所解锁的内容外，其余全部进度将会重置'],
    [/^One more level would increase ✨Divine Spark gain at Zone (.+) by (.+), and (.+) at Zone (.+)$/, '再升一级可使$1区域的✨神性火花获取量提升$2，$4区域提升$3'],
    [/^Skipped (.+) Tasks thanks to Mastery of Time$/, '由于对时间的掌握，跳过了 $1 个任务'],
    [/^(.+), multiplied by (.+) for each Zone past (.+)$/, '$1 乘以 $2（每个区域），对于超过 $3 的区域数量依次递增。'],
    [/^Toggle between no automation, and automating Tasks until the specified Zone (.+) is reached$/, '在无自动化和自动化任务之间切换，直到到达指定的区域 $1'],
    [/^Disabled due to the target Zone (.+) not being higher than the current Zone (.+)$/, '由于目标区域 $1 的高度未高于当前区域 $2，因此导致无法继续操作。'],
    [/^You\'ve now done your (.+) Energy Reset$/, '你已完成第 $1 次能量重置'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) \(x([\d\.]+) speed\)$/, '+$1 (x$2 速度)'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^Max 🔋Energy: \+([\d\.]+) \(Energetic Memory Perk\)$/, '最大🔋能量：+$1（能量记忆特权）'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Task speed$/, '+$1% 任务速度'],
    [/^([\d\.]+)\% each$/, '$1% 每个'],
    [/^\+([\d\.]+) and \+([\d\.]+)\%$/, '+$1 和 +$2%'],
    [/^([\d\.]+)\% reduction$/, '$1% 降价'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\-\- ([\d\.,]+) new repeatable Prestige upgrades$/, '-- $1 新可重复声望升级'],
    [/^\-\- ([\d\.,]+) new Perks$/, '-- $1 新特权'],
    [/^\-\- ([\d\.,]+) new Artifact$/, '-- $1 新神器'],
    [/^\-\- ([\d\.,]+) new Items$/, '-- $1 新物品'],
    [/^\-\- ([\d\.,]+) new Bosses$/, '-- $1 新Boss'],
    [/^\-\- ([\d\.,]+) new Prestige upgrades$/, '-- $1 新声望升级'],
    [/^([\d\.,]+) 📚Books$/, '$1 📚书'],
    [/^([\d\.,]+) 🍄Mushrooms$/, '$1 🍄蘑菇'],
    [/^([\d\.,]+) 🦴Oracle Bones$/, '$1 🦴甲骨'],
    [/^([\d\.,]+) 💰Coins$/, '$1 💰金币'],
    [/^([\d\.,]+) 💎Goblin Treasure$/, '$1 💎哥布林宝藏'],
    [/^([\d\.,]+) 🔗City Chain$/, '$1 🔗城市链接'],
    [/^([\d\.,]+) 🧥Worm Hide Coat$/, '$1 🧥虫皮大衣'],
    [/^([\d\.,]+) 🪓Goblin Waraxe$/, '$1 🪓哥布林战斧'],
    [/^([\d\.,]+) 🌵Cactuses$/, '$1 🌵仙人掌'],
    [/^([\d\.,]+) 🌿Reagents$/, '$1 🌿试剂'],
    [/^([\d\.,]+) 🔥Firemaking Kits$/, '$1 🔥生火工具'],
    [/^([\d\.,]+) 🧞Djinn Lamps$/, '$1 🧞精灵之灯'],
    [/^([\d\.,]+) 🌲Magical Roots$/, '$1 🌲魔法根'],
    [/^([\d\.,]+) 🎒Travel Equipment$/, '$1 🎒旅行装备'],
    [/^([\d\.,]+) 🐺Werewolf Furs$/, '$1 🐺狼人皮草'],
    [/^([\d\.,]+) 🔪Bandit Weapons$/, '$1 🔪暗行者武器'],
    [/^([\d\.,]+) 💧Oasis Water$/, '$1 💧绿洲水'],
    [/^([\d\.,]+) 📦Goblin Supplies$/, '$1 📦哥布林物资'],
    [/^([\d\.,]+) 🏹Arrows$/, '$1 🏹箭'],
    [/^([\d\.,]+) 🌠Magical Essences$/, '$1 🌠魔法精华'],
    [/^([\d\.,]+) ⛺Camping Equipment$/, '$1 ⛺营地装备'],
    [/^([\d\.,]+) 🐲Dragon Scales$/, '$1 🐲龙鳞'],
    [/^([\d\.,]+) 👢Knightly Boots$/, '$1 👢骑士靴'],
    [/^([\d\.,]+) 🛠️Crafting Recipes$/, '$1 🛠️制作配方'],
    [/^([\d\.,]+) 🏺Magical Vessels$/, '$1 🏺魔法容器'],
    [/^([\d\.,]+) 🕯️Mystic Incense$/, '$1 🕯️神秘香'],
    [/^Unlocked in Zone ([\d\.,]+)$/, '解锁于区域 $1'],
    [/^Gives ([\d\.,]+) 🔋Energy each$/, '每个给予 $1 🔋能量'],
    [/^Gained ([\d\.,]+) 🔋Energy$/, '获得 $1 🔋能量'],
    [/^Used ([\d\.,]+) ✨Divine Sparks$/, '使用了 $1 ✨神圣火花'],
    [/^Used ([\d\.,]+) 🍱Army Food$/, '使用了 $1 🍱军团食粮'],
    [/^Used ([\d\.,]+) 🩸Ritual Sacrifice$/, '使用了 $1 🩸仪式献祭'],
    [/^Used ([\d\.,]+) 📼Recordings$/, '使用了 $1 📼记录'],
    [/^Used ([\d\.,]+) ☯️Ritual Symbol$/, '使用了 $1 ☯️仪式徽记'],
    [/^Used ([\d\.,]+) 👓Glasses$/, '使用了 $1 👓眼镜'],
    [/^Used ([\d\.,]+) 🍲Food$/, '使用了 $1 🍲食物'],
    [/^Used ([\d\.,]+) 🏹Arrow$/, '使用了 $1 🏹箭'],
    [/^You've now done your ([\d\.,]+)th Energy Reset$/, '现在你已经完成了第 $1 次能量重置'],
    [/^You've now done your ([\d\.,]+)st Energy Reset$/, '现在你已经完成了第 $1 次能量重置'],
    [/^This was your ([\d\.,]+)th Energy Reset$/, '这是你的第 $1 次'],
    [/^This was your ([\d\.,]+)nd Energy Reset$/, '这是你的第 $1 次'],
    [/^Used ([\d\.,]+) 🦟Cave Insects$/, '使用了 $1 🦟洞穴昆虫'],
    [/^Used ([\d\.,]+) 🏺Magical Vessels$/, '使用了 $1 🏺魔法容器'],
    [/^Used ([\d\.,]+) 🛠️Crafting Recipes$/, '使用了 $1 🛠️制作配方'],
    [/^Used ([\d\.,]+) 👢Knightly Boots$/, '使用了 $1 👢骑士战靴'],
    [/^Used ([\d\.,]+) 🐲Dragon Scales$/, '使用了 $1 🐲龙鳞'],
    [/^Used ([\d\.,]+) 🌠Magical Essences$/, '使用了 $1 🌠魔法精华'],
    [/^Used ([\d\.,]+) 💰Coin$/, '使用了 $1 💰金币'],
    [/^Used ([\d\.,]+) 💰Coins$/, '使用了 $1 💰金币'],
    [/^Used ([\d\.,]+) 🏹Arrows$/, '使用了 $1 🏹箭'],
    [/^Used ([\d\.,]+) 🐟Fish$/, '使用了 $1 🐟鱼'],
    [/^Used ([\d\.,]+) 📚Books$/, '使用了 $1 📚书'],
    [/^Used ([\d\.,]+) 📚Book$/, '使用了 $1 📚书'],
    [/^Used ([\d\.,]+) 🍄Mushrooms$/, '使用了 $1 🍄蘑菇'],
    [/^Used ([\d\.,]+) 🍄Mushroom$/, '使用了 $1 🍄蘑菇'],
    [/^Used ([\d\.,]+) 🌿Reagents$/, '使用了 $1 🌿试剂'],
    [/^Used ([\d\.,]+) 🌿Reagent$/, '使用了 $1 🌿试剂'],
    [/^Used ([\d\.,]+) 💧Oasis Water$/, '使用了 $1 💧绿洲水'],
    [/^Used ([\d\.,]+) 🌲Magical Roots$/, '使用了 $1 🌲魔法根'],
    [/^Used ([\d\.,]+) 🌲Magical Root$/, '使用了 $1 🌲魔法根'],
    [/^Used ([\d\.,]+) 🐺Werewolf Furs$/, '使用了 $1 🐺狼人皮毛'],
    [/^Used ([\d\.,]+) 🐺Werewolf Fur$/, '使用了 $1 🐺狼人皮毛'],
    [/^Used ([\d\.,]+) 🦴Oracle Bones$/, '使用了 $1 🦴甲骨'],
    [/^Used ([\d\.,]+) 🦴Oracle Bone$/, '使用了 $1 🦴甲骨'],
    [/^Used ([\d\.,]+) 🔪Bandit Weapons$/, '使用了 $1 🔪暗行者武器'],
    [/^Used ([\d\.,]+) 🔪Bandit Weapon$/, '使用了 $1 🔪暗行者武器'],
    [/^Used ([\d\.,]+) 🌵Cactus$/, '使用了 $1 🌵仙人掌'],
    [/^Used ([\d\.,]+) 🌵Cactuses$/, '使用了 $1 🌵仙人掌'],
    [/^Used ([\d\.,]+) 🔗City Chain$/, '使用了 $1 🔗城市链'],
    [/^Used ([\d\.,]+) 🔗City Chains$/, '使用了 $1 🔗城市链'],
    [/^Used ([\d\.,]+) 💎Goblin Treasure$/, '使用了 $1 💎哥布林宝藏'],
    [/^Used ([\d\.,]+) 💎Goblin Treasures$/, '使用了 $1 💎哥布林宝藏'],
    [/^Used ([\d\.,]+) 🧞Djinn Lamp$/, '使用了 $1 🧞精灵之灯'],
    [/^Used ([\d\.,]+) 🧞Djinn Lamps$/, '使用了 $1 🧞精灵之灯'],
    [/^Used ([\d\.,]+) 🕯️Mystic Incense$/, '使用了 $1 🕯️神秘香'],
    [/^Used ([\d\.,]+) 🦑Calamari$/, '使用了 $1 🦑鱿鱼'],
    [/^Used ([\d\.,]+) 🧥Worm Hide Coat$/, '使用了 $1 🧥虫皮大衣'],
    [/^Used ([\d\.,]+) 🪓Goblin Waraxe$/, '使用了 $1 🪓哥布林战斧'],
    [/^Used ([\d\.,]+) 🪓Goblin Waraxes$/, '使用了 $1 🪓哥布林战斧'],
    [/^Used ([\d\.,]+) 📦Goblin Supplies$/, '使用了 $1 📦哥布林补给'],
    [/^Used ([\d\.,]+) 🎒Travel Equipment$/, '使用了 $1 🎒旅行装备'],
    [/^Used ([\d\.,]+) 🔥Firemaking Kits$/, '使用了 $1 🔥生火工具'],
    [/^Used ([\d\.,]+) 🔥Firemaking Kit$/, '使用了 $1 🔥生火工具'],
    [/^Used ([\d\.,]+) ⛺Camping Equipment$/, '使用了 $1 ⛺露营装备'],
    [/^Used ([\d\.,]+) 🕸️Dreamcatcher$/, '使用了 $1 🕸️捕梦网'],
    [/^Used ([\d\.,]+) 💍Magic Ring$/, '使用了 $1 💍魔法戒指'],
    [/^Used ([\d\.,]+) Items$/, '使用了 $1 物品'],
    [/^Copied ([\d\.,]+) Items$/, '复制了 $1 物品'],
    [/^🔋Energy use per second: ([\d\.,]+) \(in Zone ([\d\.,]+)\)$/, '🔋每秒能量消耗: $1 (在区域 $2)'],
    [/^Zone ([\d\.,]+)$/, '区域 $1'],
    [/^Automate To Zone ([\d\.,]+)$/, '自动到区域 $1'],
    [/^Cost: ([\d\.,]+)$/, '成本: $1'],
    [/^Cost: ([\d\.,]+)(.+)$/, '成本: $1$2'],
    [/^Level: ([\d\.,]+)$/, '等级: $1'],
    [/^This is Zone ([\d\.,]+) of ([\d\.,]+)$/, '当前在区域 $1 \/ $2'],
    [/^task in Zone ([\d\.,]+)$/, '任务在区域 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Undo Use of ([\d\.,]+) ⚡Bottled Lightning$/, '撤销使用 $1 ⚡瓶装闪电'],
    [/^Skipped to Zone ([\d\.,]+) thanks to ⌚Minor Time Compression$/, '由于⌚次要时间压缩，跳过到区域 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);